# Modelos Lineales Mixtos {#lmm}
Los modelos lineales mixtos fueron propuestos por [@LairdWare82] y en ellos se asume que existe una relación entre el vector de observaciones $\boldsymbol{Y}_i$ del sujeto o grupo $i$ y las covariables por medio de la siguiente expresión 

\begin{equation}
\begin{aligned}
\boldsymbol{Y}_i \mid \boldsymbol{b}_i &\sim \mathcal{N}(\boldsymbol{X}_i \boldsymbol{\beta} + \boldsymbol{Z}_i \boldsymbol{b}_i, \boldsymbol{\Sigma}_i), \\
\boldsymbol{b}_i &\sim \mathcal{N}(\boldsymbol{0}, \boldsymbol{D}),
\end{aligned}
(\#eq:lmm1)
\end{equation}

donde $\boldsymbol{X}_i$ y $\boldsymbol{Z}_i$ son matrices de diseño conocidas con la información de las covariables, siendo $\boldsymbol{X}_i$ de dimensión $n_i \times p$ y $\boldsymbol{Z}_i$ de dimensión $n_i \times q$. El elemento $\boldsymbol{\beta}$ representa el vector de efectos fijos general, $\boldsymbol{b}_i$ el vector de efectos aleatorios exclusivo para el grupo $i$.

El vector $\boldsymbol{b}_i$ en la expresión \@ref(eq:lmm1) es llamado efecto aleatorio porque éste cambia la media de sujeto a sujeto y su función es la de mejorar el ajuste general dado por el elemento $\boldsymbol{X}_i \boldsymbol{\beta}$ al agregar la cantidad $\boldsymbol{Z}_i \boldsymbol{b}_i$. El modelo dado en la expresión \@ref(eq:lmm1) es llamado también modelo mixto porque involucra tanto efectos fijos ($\boldsymbol{\beta}$) como efectos aleatorios ($\boldsymbol{b}_i$).

La distribución marginal de $\boldsymbol{Y}_i$ está dada por

\begin{equation}
f_i(\boldsymbol{Y}_i) = \int f(\boldsymbol{Y}_i | \boldsymbol{b}_i) f(\boldsymbol{b}_i) \, d \boldsymbol{b}_i
\end{equation}

donde $f(\boldsymbol{Y}_i | \boldsymbol{b}_i)$ y $f(\boldsymbol{b}_i)$ corresponden a las densidades normales mostradas en la expresión \@ref(eq:lmm1). Esta distribución marginal tiene forma cerrada y se puede mostrar fácilmente que la distribución de $\boldsymbol{Y}_i$ es una normal multivariada con vector de medias y matriz de covarianzas como se muestra a continuación.

\begin{equation}
\boldsymbol{Y}_i \sim \mathcal{N}(\boldsymbol{X}_i \boldsymbol{\beta}, \boldsymbol{V}_i),
\end{equation}

donde $\boldsymbol{V}_i=\boldsymbol{Z}_i \boldsymbol{D} \boldsymbol{Z}_i^\top + \boldsymbol{\Sigma}_i$. El vector de parámetros en este caso es $\boldsymbol{\theta}=(\boldsymbol{\beta}, \boldsymbol{\alpha})^\top$ donde $\boldsymbol{\alpha}$ consiste de los $q(q+1)/2$ elementos diferentes de la matriz $\boldsymbol{D}$ y todos los elementos de la matriz $\boldsymbol{\Sigma}_i$.

## Entrevista con Jim Ware y Nan Laird

<iframe width="560" height="315" src="https://www.youtube.com/embed/dUphXonH8do" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

