<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Aplicación con nlme | Modelos Mixtos con R</title>
  <meta name="description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Aplicación con nlme | Modelos Mixtos con R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Aplicación con nlme | Modelos Mixtos con R" />
  
  <meta name="twitter:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández Barajas" />
<meta name="author" content="Jorge Leonardo López Martínez" />


<meta name="date" content="2022-10-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pac-nlme.html"/>
<link rel="next" href="apli-rat-pup.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Mixtos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#la-complejidad-estructural-tenida-en-cuenta-por-los-modelos-mixtos"><i class="fa fa-check"></i><b>1.1</b> La complejidad estructural tenida en cuenta por los modelos mixtos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reg-lin.html"><a href="reg-lin.html"><i class="fa fa-check"></i><b>2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reg-lin.html"><a href="reg-lin.html#modelo-estadístico"><i class="fa fa-check"></i><b>2.1</b> Modelo estadístico</a></li>
<li class="chapter" data-level="2.2" data-path="reg-lin.html"><a href="reg-lin.html#verosimilitud-del-modelo"><i class="fa fa-check"></i><b>2.2</b> Verosimilitud del modelo</a>
<ul>
<li class="chapter" data-level="" data-path="reg-lin.html"><a href="reg-lin.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lmm.html"><a href="lmm.html"><i class="fa fa-check"></i><b>3</b> Modelos Lineales Mixtos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lmm.html"><a href="lmm.html#entrevista-con-jim-ware-y-nan-laird"><i class="fa fa-check"></i><b>3.1</b> Entrevista con Jim Ware y Nan Laird</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>4</b> Aplicaciones shiny</a></li>
<li class="chapter" data-level="5" data-path="pac-lme4.html"><a href="pac-lme4.html"><i class="fa fa-check"></i><b>5</b> Paquete <strong>lme4</strong></a>
<ul>
<li class="chapter" data-level="5.1" data-path="pac-lme4.html"><a href="pac-lme4.html#función-lmer"><i class="fa fa-check"></i><b>5.1</b> Función <code>lmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-normal-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-recuperando-los-interceptos-aleatorios"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="5.2" data-path="pac-lme4.html"><a href="pac-lme4.html#función-glmer"><i class="fa fa-check"></i><b>5.2</b> Función <code>glmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-gamma-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-inversa-gaussiana-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i>Ejemplo: modelo inversa gaussiana con intercepto y pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="apli-lme4.html"><a href="apli-lme4.html"><i class="fa fa-check"></i><b>6</b> Aplicación con <code>lme4</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-lme4.html"><a href="apli-lme4.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="pac-nlme.html"><a href="pac-nlme.html"><i class="fa fa-check"></i><b>7</b> Paquete <strong>nlme</strong></a>
<ul>
<li class="chapter" data-level="7.1" data-path="pac-nlme.html"><a href="pac-nlme.html#función-lme"><i class="fa fa-check"></i><b>7.1</b> Función <code>lme</code></a></li>
<li class="chapter" data-level="" data-path="pac-nlme.html"><a href="pac-nlme.html#ejemplo-modelo-normal-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apli-nlme.html"><a href="apli-nlme.html"><i class="fa fa-check"></i><b>8</b> Aplicación con <code>nlme</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-nlme.html"><a href="apli-nlme.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="apli-rat-pup.html"><a href="apli-rat-pup.html"><i class="fa fa-check"></i><b>9</b> Aplicación rat pup</a></li>
<li class="chapter" data-level="10" data-path="estim.html"><a href="estim.html"><i class="fa fa-check"></i><b>10</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estim.html"><a href="estim.html#ml-y-reml"><i class="fa fa-check"></i><b>10.1</b> ML y REML</a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-lme4"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>lme4</strong></a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-nlme"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>nlme</strong></a></li>
<li class="chapter" data-level="12.2" data-path="var-fun.html"><a href="var-fun.html"><i class="fa fa-check"></i><b>12.2</b> varFixed</a></li>
<li class="chapter" data-level="" data-path="var-fun.html"><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cuantitativa"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cuantitativa</a></li>
<li class="chapter" data-level="12.3" data-path="var-fun.html"><a href="var-fun.html#varident"><i class="fa fa-check"></i><b>12.3</b> varIdent</a></li>
<li class="chapter" data-level="" data-path="var-fun.html"><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cualitativa"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cualitativa</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="predict-new.html"><a href="predict-new.html"><i class="fa fa-check"></i><b>13</b> Predicción</a></li>
<li class="chapter" data-level="14" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>14</b> Modelos Lineales Generalizados Mixtos</a>
<ul>
<li class="chapter" data-level="14.1" data-path="glmm.html"><a href="glmm.html#videos-de-apoyo"><i class="fa fa-check"></i><b>14.1</b> Videos de apoyo</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html"><i class="fa fa-check"></i><b>15</b> Paquete <strong>glmmTMB</strong></a>
<ul>
<li class="chapter" data-level="15.1" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#función-glmmtmb"><i class="fa fa-check"></i><b>15.1</b> Función <code>glmmTMB</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-normal-con-intercepto-aleatorio-2"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-recuperando-los-interceptos-aleatorios-1"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-gamma-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="pac-glmm.html"><a href="pac-glmm.html"><i class="fa fa-check"></i><b>16</b> Paquete <strong>glmm</strong></a>
<ul>
<li class="chapter" data-level="16.1" data-path="pac-glmm.html"><a href="pac-glmm.html#función-glmm"><i class="fa fa-check"></i><b>16.1</b> Función <code>glmm</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmm.html"><a href="pac-glmm.html#ejemplo-modelo-poisson-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Poisson con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="pac-MASS.html"><a href="pac-MASS.html"><i class="fa fa-check"></i><b>17</b> Paquete <strong>MASS</strong></a>
<ul>
<li class="chapter" data-level="17.1" data-path="pac-MASS.html"><a href="pac-MASS.html#función-glmmpql"><i class="fa fa-check"></i><b>17.1</b> Función <code>glmmPQL</code></a></li>
<li class="chapter" data-level="" data-path="pac-MASS.html"><a href="pac-MASS.html#ejemplo-modelo-bernoulli-binomial-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Bernoulli (binomial) con intercepto aleatorio</a></li>
<li class="chapter" data-level="17.2" data-path="pac-MASS.html"><a href="pac-MASS.html#what-it-means-for-aic-na-in-glmmpql-mass-summary-output"><i class="fa fa-check"></i><b>17.2</b> what it means for AIC NA in glmmPQL (MASS) summary output?</a></li>
<li class="chapter" data-level="17.3" data-path="pac-MASS.html"><a href="pac-MASS.html#two-questions-on-the-results-from-glmmpqlmass"><i class="fa fa-check"></i><b>17.3</b> Two questions on the results from glmmPQL(MASS)</a></li>
<li class="chapter" data-level="17.4" data-path="pac-MASS.html"><a href="pac-MASS.html#how-do-i-interpret-the-variance-of-random-effect-in-a-generalized-linear-mixed-model"><i class="fa fa-check"></i><b>17.4</b> How do I interpret the variance of random effect in a generalized linear mixed model?</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="glmm_poisson.html"><a href="glmm_poisson.html"><i class="fa fa-check"></i><b>18</b> GLMM Poisson</a></li>
<li class="chapter" data-level="19" data-path="glmm_gamma.html"><a href="glmm_gamma.html"><i class="fa fa-check"></i><b>19</b> GLMM gamma</a></li>
<li class="chapter" data-level="20" data-path="residuals.html"><a href="residuals.html"><i class="fa fa-check"></i><b>20</b> Diagnósticos con DHARMa</a>
<ul>
<li class="chapter" data-level="" data-path="residuals.html"><a href="residuals.html#ejemplo-modelo-gamma-mixto"><i class="fa fa-check"></i>Ejemplo: modelo gamma mixto</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="simul-glmm.html"><a href="simul-glmm.html"><i class="fa fa-check"></i><b>21</b> Simulación de glmm</a></li>
<li class="chapter" data-level="22" data-path="blobs.html"><a href="blobs.html"><i class="fa fa-check"></i><b>22</b> Otro material interesante</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Mixtos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="apli-nlme" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Aplicación con <code>nlme</code><a href="apli-nlme.html#apli-nlme" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se mostrará como usar el paquete <code>nlme</code> para la aplicación de modelos mixtos con la base de datos <code>Oxboys</code> del mismo paquete.</p>
<p><img src="images/crecimiento_chicos.png" width="80%" style="display: block; margin: auto;" /></p>
<p>A continuación la base de datos a utilizar.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="apli-nlme.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb55-2"><a href="apli-nlme.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Oxboys)</span></code></pre></div>
<pre><code>## Grouped Data: height ~ age | Subject
##   Subject     age height Occasion
## 1       1 -1.0000  140.5        1
## 2       1 -0.7479  143.4        2
## 3       1 -0.4630  144.8        3
## 4       1 -0.1643  147.1        4
## 5       1 -0.0027  147.7        5
## 6       1  0.2466  150.2        6</code></pre>
<p>Esta base de datos sobre crecimiento contiene la información sobre altura (<code>heigth</code>), edad estandarizada (<code>age</code>) de un grupo de 26 jóvenes. Como la base de datos <code>Oxboys</code> es de la clase groupedData, es posible aplicar un <code>plot</code> directamente y el resultado se muestra continuación.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="apli-nlme.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Oxboys)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/plot_oxboys_nlme-1.png" width="672" /></p>
<div style="-moz-box-shadow: 1px 1px 3px 2px #00ffff;
  -webkit-box-shadow: 1px 1px 3px 2px #00ffff;
  box-shadow:         1px 1px 3px 2px #00ffff;">

<div class="rmdtip">
Es posible convertir un data.frame para que tenga la clase groupedData, consulte la ayuda de la función <code>groupedData</code> del paquete <code>nlme</code> para más detalles.
</div>
</div>
<p>De la figura anterior vemos que las curvas de crecimiento inician a diferente altura (intercepto) y que la pendiente del crecimiento no son todas iguales, por ejemplo, el individuo 21 creció más rápido que el individuo 3. Esto nos hace pensar que un modelo con intercepto y pendiente aleatoria podrían ser adecuados para modelar el crecimiento.</p>
<p>En las siguientes ecuaciones se resume el modelo matemático que interesa en esta situación.</p>
<p><span class="math display">\[\begin{align*}
Height_{ij} | b_0, b_1 &amp;\sim  N(\mu_{ij}, \sigma^2_{Heigth}) \\
\mu_{ij} &amp;= \beta_0 + \beta_1 Age_{ij} + b_{0i} + b_{1i} Age_{ij} \\
\left (
\begin{matrix}
b_{0} \\ b_{1}
\end{matrix}
\right ) &amp;\sim
N\left ( \left ( \begin{matrix}
0 \\ 0
\end{matrix} \right ),
\left ( \begin{matrix}
\sigma^2_{b0} &amp; \sigma_{b01} \\
\sigma_{b01} &amp; \sigma^2_{b1}
\end{matrix} \right )
\right )
\end{align*}\]</span></p>
<p>El vector de parámetros para este modelo sería <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0, \beta_1, \sigma_{height}, \sigma_{b0}, \sigma_{b1}, \sigma_{b0b1})^\top\)</span>.</p>
<p>Para ajustar este modelo a los datos con el paquete <code>nlme</code> podemos usar el siguiente código.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="apli-nlme.html#cb58-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lme</span>(height <span class="sc">~</span> age, <span class="at">random=</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> age <span class="sc">|</span> Subject, <span class="at">data=</span>Oxboys, <span class="at">method=</span><span class="st">&quot;REML&quot;</span>)</span></code></pre></div>
<p>Para obtener la tabla de resumen usamos:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="apli-nlme.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Oxboys 
##       AIC      BIC    logLik
##   736.091 756.7714 -362.0455
## 
## Random effects:
##  Formula: ~1 + age | Subject
##  Structure: General positive-definite, Log-Cholesky parametrization
##             StdDev   Corr  
## (Intercept) 8.081077 (Intr)
## age         1.680717 0.641 
## Residual    0.659889       
## 
## Fixed effects:  height ~ age 
##                 Value Std.Error  DF  t-value p-value
## (Intercept) 149.37175 1.5854173 207 94.21605       0
## age           6.52547 0.3363003 207 19.40370       0
##  Correlation: 
##     (Intr)
## age 0.628 
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.65092109 -0.57493341 -0.02842894  0.59604254  2.60496077 
## 
## Number of Observations: 234
## Number of Groups: 26</code></pre>
<p>De la salida anterior se obtiene que <span class="math inline">\(\hat{\boldsymbol{\Theta}}=(\hat{\beta}_0=149.37, \hat{\beta}_1=6.53, \hat{\sigma}_{height}=0.66, \hat{\sigma}_{b0}=8.08, \hat{\sigma}_{b1}=1.68, \hat{\sigma}_{b0b1}=8.71)^\top\)</span>. La estimación <span class="math inline">\(\hat{\sigma}_{b0b1}\)</span> no aparece directamente en el summary pero se obtiene utilizando la ecuación <span class="math inline">\(Cor=Cov/(\sigma_1 \sigma_2)\)</span> que relaciona <a href="https://en.wikipedia.org/wiki/Correlation_and_dependence">correlación</a>, covarianza y desviaciones de los efectos aleatorios.</p>
<p>Usando la información anterior se puede escribir el modelo ajustado de la siguiente manera.</p>
<p><span class="math display">\[\begin{align*}
Height_{ij} &amp;\sim  N(\hat{\mu}_{ij}, 0.66^2) \\
\hat{\mu}_{ij} &amp;= 149.37 + 6.53 Age_{ij} + b_{0i} + b_{1i} Age_{ij} \\
\left (
\begin{matrix}
b_{0} \\ b_{1}
\end{matrix}
\right ) &amp;\sim
N\left ( \left ( \begin{matrix}
0 \\ 0
\end{matrix} \right ),
\left ( \begin{matrix}
8.08^2 &amp; 8.71 \\
8.71 &amp; 1.68^2
\end{matrix} \right )
\right ).
\end{align*}\]</span></p>
<p>Los elementos <span class="math inline">\(b_{0i}\)</span> y <span class="math inline">\(b_{1i}\)</span> se deben substituir por sus respectivas predicciones <span class="math inline">\(\tilde{b}_{0i}\)</span> y <span class="math inline">\(\tilde{b}_{1i}\)</span> y se pueden obtener del modelo ajustado así:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="apli-nlme.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(fit)</span></code></pre></div>
<pre><code>##    (Intercept)         age
## 10 -19.0972476 -2.78657472
## 26 -11.3675996 -0.97474075
## 25 -10.1595528 -2.42702035
## 9  -11.2213331 -0.58069044
## 2   -6.5096277 -1.07136271
## 6   -2.5902388 -2.41771656
## 7   -3.2473132 -1.46379286
## 17  -6.3744842  1.89443713
## 16  -1.8344703 -1.86707015
## 15  -5.0856366  0.51526141
## 8   -1.0776201 -0.06615528
## 20   2.0850836 -1.99239802
## 1   -1.2464285  0.59919226
## 18   1.8031920 -0.51486646
## 5    2.0531168 -0.24308081
## 23   1.6937341  0.63140824
## 11   0.6839704  1.85733185
## 21   1.1525543  0.91894343
## 3    6.2613001 -1.58181075
## 24   3.7645669  0.25652772
## 22   5.1957592  1.50551719
## 12   7.4308033  0.52297645
## 13   6.7004368  1.89758007
## 14  10.0986013  2.09367207
## 19  15.1957040  2.50720025
## 4   15.6927297  2.78723179</code></pre>
<p>Los valores de los efectos fijos estimados se pueden obtener así:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="apli-nlme.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(fit)</span></code></pre></div>
<pre><code>## (Intercept)         age 
##  149.371753    6.525469</code></pre>
<p>Usando la información de los efectos fijo y aleatorios obtenidos antes, es posible escribir la ecuación del modelo para cada individuo. Los efectos fijos estimados fueron <span class="math inline">\(\hat{\beta}_0 \approx 149.37\)</span> y <span class="math inline">\(\hat{\beta}_1\approx 6.53\)</span>. Para el sujeto # 10 se obtuvo <span class="math inline">\(\tilde{b}_{0, i=10} \approx -19.10\)</span> y <span class="math inline">\(\tilde{b}_{1, i=10} \approx -2.79\)</span>, así la media del individuo # 10 se calcula así:</p>
<p><span class="math display">\[\begin{align*}
\hat{\mu}_{i=10, j} &amp;= \hat{\beta}_0 + \hat{\beta}_0 \, Age_{i=10, j} + \tilde{b}_{0, i=10} + \tilde{b}_{1, i=10} \, Age_{i=10, j} \\
\hat{\mu}_{i=10, j} &amp;= 149.37 + 6.53 \, Age_{i=10, j} - 19.10 - 2.79 \, Age_{i=10, j} \\
\hat{\mu}_{i=10, j} &amp;= 130.27 + 3.74 \, Age_{i=10, j}
\end{align*}\]</span></p>
<p>Lo anterior se puede resumir en el siguiente modelo.</p>
<p><span class="math display">\[\begin{align*}
Height_{i=10, j} &amp;\sim  N(\hat{\mu}_{i=10, j}, \hat{\sigma}^2_{Height}) \\
\hat{\mu}_{i=10, j} &amp;= 130.27 + 3.74 \, Age_{i=10, j} \\
\hat{\sigma}_{Height} &amp;= 0.66
\end{align*}\]</span></p>
<p>La expresión anterior para cada individuo con los efectos finales (fijos y aleatorios) se puede obtener con R así:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="apli-nlme.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code></pre></div>
<pre><code>##    (Intercept)      age
## 10    130.2745 3.738894
## 26    138.0042 5.550728
## 25    139.2122 4.098448
## 9     138.1504 5.944778
## 2     142.8621 5.454106
## 6     146.7815 4.107752
## 7     146.1244 5.061676
## 17    142.9973 8.419906
## 16    147.5373 4.658399
## 15    144.2861 7.040730
## 8     148.2941 6.459313
## 20    151.4568 4.533071
## 1     148.1253 7.124661
## 18    151.1749 6.010602
## 5     151.4249 6.282388
## 23    151.0655 7.156877
## 11    150.0557 8.382801
## 21    150.5243 7.444412
## 3     155.6331 4.943658
## 24    153.1363 6.781996
## 22    154.5675 8.030986
## 12    156.8026 7.048445
## 13    156.0722 8.423049
## 14    159.4704 8.619141
## 19    164.5675 9.032669
## 4     165.0645 9.312700</code></pre>
<p>En la presente aplicación es posible incluir la recta de regresión para cada individuo al diagrama de dispersión original. El código de R para obtener esto es el siguiente.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="apli-nlme.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb67-2"><a href="apli-nlme.html#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(height <span class="sc">~</span> age <span class="sc">|</span> Subject, <span class="at">data=</span>Oxboys, <span class="at">fit=</span>fit,</span>
<span id="cb67-3"><a href="apli-nlme.html#cb67-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">strip=</span><span class="fu">strip.custom</span>(<span class="at">bg=</span><span class="st">&quot;white&quot;</span>), </span>
<span id="cb67-4"><a href="apli-nlme.html#cb67-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">16</span>, <span class="at">cex=</span><span class="fl">0.7</span>, <span class="at">col=</span><span class="st">&#39;indianred1&#39;</span>,</span>
<span id="cb67-5"><a href="apli-nlme.html#cb67-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">panel =</span> <span class="cf">function</span>(x, y, ..., fit, subscripts) {</span>
<span id="cb67-6"><a href="apli-nlme.html#cb67-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">panel.xyplot</span>(x, y, ...)</span>
<span id="cb67-7"><a href="apli-nlme.html#cb67-7" aria-hidden="true" tabindex="-1"></a>         ypred <span class="ot">&lt;-</span> <span class="fu">fitted</span>(fit)[subscripts]</span>
<span id="cb67-8"><a href="apli-nlme.html#cb67-8" aria-hidden="true" tabindex="-1"></a>         <span class="fu">panel.lines</span>(x, ypred, <span class="at">col=</span><span class="st">&quot;deepskyblue3&quot;</span>, <span class="at">lwd=</span><span class="dv">1</span>)</span>
<span id="cb67-9"><a href="apli-nlme.html#cb67-9" aria-hidden="true" tabindex="-1"></a>       },</span>
<span id="cb67-10"><a href="apli-nlme.html#cb67-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab=</span><span class="st">&quot;Height (cm)&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Centered age&quot;</span>)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/evol_fit_nlme-1.png" width="672" /></p>
<p>En la figura anterior se tienen las observaciones (crecimiento) representado por los puntos rojos, adicionalmente, aparece una recta de color azul que representa la recta de regresión para cada individuo. De la figura se observa que la linea logra explicar la evolución del crecimiento para cada individuo.</p>
<div id="ejercicios-1" class="section level2 unnumbered hasAnchor">
<h2>Ejercicios<a href="apli-nlme.html#ejercicios-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Repita el ejercicio anterior considerando un modelo sólo con intercepto aleatorio. Dibuje las rectas de regresión para cada individuo. ¿Qué opina de este modelo?</p></li>
<li><p>Repita el ejercicio anterior considerando un modelo sólo con pendiente aleatoria. Dibuje las rectas de regresión para cada individuo. ¿Qué opina de este modelo?</p></li>
<li><p>Estime la estatura para el individuo # 3 cuando su edad centrada sea de 1.1.</p></li>
<li><p>Replique los ejemplo <a href="https://socialsciences.mcmaster.ca/jfox/Books/Companion-1E/appendix-mixed-models.pdf">de este documento</a>.</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pac-nlme.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="apli-rat-pup.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_modelos_mixtos/edit/master/305-apli-nlme.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
