<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Aplicación con lme4 | Modelos Mixtos con R</title>
  <meta name="description" content="Este libro es para ….." />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Aplicación con lme4 | Modelos Mixtos con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Este libro es para ….." />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Aplicación con lme4 | Modelos Mixtos con R" />
  
  <meta name="twitter:description" content="Este libro es para ….." />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Freddy Hernández Barajas" />
<meta name="author" content="Jorge Leonardo López Martínez" />


<meta name="date" content="2020-02-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="references.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Mixtos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="reg-lin.html"><a href="reg-lin.html"><i class="fa fa-check"></i><b>1</b> Regresión lineal</a><ul>
<li class="chapter" data-level="1.1" data-path="reg-lin.html"><a href="reg-lin.html#modelo-estadístico"><i class="fa fa-check"></i><b>1.1</b> Modelo estadístico</a></li>
<li class="chapter" data-level="1.2" data-path="reg-lin.html"><a href="reg-lin.html#verosimilitud-del-modelo"><i class="fa fa-check"></i><b>1.2</b> Verosimilitud del modelo</a><ul>
<li class="chapter" data-level="" data-path="reg-lin.html"><a href="reg-lin.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="mod-mix.html"><a href="mod-mix.html"><i class="fa fa-check"></i><b>2</b> Modelos Mixtos</a></li>
<li class="chapter" data-level="3" data-path="pac-lme4.html"><a href="pac-lme4.html"><i class="fa fa-check"></i><b>3</b> Paquete <strong>lme4</strong></a><ul>
<li class="chapter" data-level="3.1" data-path="pac-lme4.html"><a href="pac-lme4.html#función-lmer"><i class="fa fa-check"></i><b>3.1</b> Función <code>lmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="pac-nlme.html"><a href="pac-nlme.html"><i class="fa fa-check"></i><b>4</b> Paquete <strong>nlme</strong></a><ul>
<li class="chapter" data-level="4.1" data-path="pac-nlme.html"><a href="pac-nlme.html#función-lme"><i class="fa fa-check"></i><b>4.1</b> Función <code>lme</code></a></li>
<li class="chapter" data-level="" data-path="pac-nlme.html"><a href="pac-nlme.html#ejemplo-modelo-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>5</b> Pruebas de hipótesis</a><ul>
<li class="chapter" data-level="5.1" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-sobre-un-parámetro-fijo-beta_k"><i class="fa fa-check"></i><b>5.1</b> Prueba de hipótesis sobre un parámetro fijo <span class="math inline">\(\beta_k\)</span></a></li>
<li class="chapter" data-level="5.2" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-sobre-un-conjunto-de-parámetros-varios-beta_k"><i class="fa fa-check"></i><b>5.2</b> Prueba de hipótesis sobre un conjunto de parámetros (varios <span class="math inline">\(\beta_k\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="apli-nlme.html"><a href="apli-nlme.html"><i class="fa fa-check"></i><b>6</b> Aplicación con <code>nlme</code></a><ul>
<li class="chapter" data-level="" data-path="apli-nlme.html"><a href="apli-nlme.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="7" data-path="aplicación-con-lme4.html"><a href="aplicación-con-lme4.html"><i class="fa fa-check"></i><b>7</b> Aplicación con <code>lme4</code></a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Mixtos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="aplicación-con-lme4" class="section level1">
<h1><span class="header-section-number">7</span> Aplicación con <code>lme4</code></h1>
<p>En este capítulo se mostrará como usar el paquete <code>lme4</code> para la aplicación de modelos mixtos con la base de datos <code>sleepstudy</code> del mismo paquete.</p>
<p>A continuación la base de datos a utilizar.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(lme4)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">head</span>(sleepstudy)</a></code></pre></div>
<pre><code>##   Reaction Days Subject
## 1 249.5600    0     308
## 2 258.7047    1     308
## 3 250.8006    2     308
## 4 321.4398    3     308
## 5 356.8519    4     308
## 6 414.6901    5     308</code></pre>
<p>Esta base de datos sobre el tiempo de reacción promedio por día para un conjunto de individuos, en un estudio de privación del sueño, contiene la información sobre el tiempo de reacción promedio (<code>Reaction</code>), el número de días de privación del sueño (<code>Days</code>), donde el día 0 corresponde al día en el que los indiviuos tenían su cantidad normal de sueño, y el número del individuo (en total 18) sobre el que se realizó la observación (<code>Subject</code>). A partir del día 0, hubo una restricción en cada individuo a 3 horas de sueño por noche.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"></a>
<a class="sourceLine" id="cb3-3" data-line-number="3"><span class="kw">ggplot</span>(sleepstudy, <span class="kw">aes</span>(<span class="dt">x =</span> Days, <span class="dt">y =</span> Reaction, <span class="dt">color =</span> Subject)) <span class="op">+</span></a>
<a class="sourceLine" id="cb3-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb3-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb3-6" data-line-number="6"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb3-7" data-line-number="7"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</a></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/plot_sleepstudy_lme4-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>De la figura anterior vemos que el tiempo de reacción promedio, tanto en el día 0 como en los siguientes días de prueba (del día 1 al día 9), son distintos en cada uno de los individuos. Esta situación conlleva a probar la hipótesis de que el tiempo de reacción promedio en una serie de pruebas varía según los individuos. Esto es, ajustar un modelo donde el intercepto y la pendiente se consideran como efectos aleatorios.</p>
<p>Un modelo lineal mixto que describe la anterior situación se puede escribir como:</p>
<p><span class="math display">\[\begin{align*} 
Reaction_{ij} &amp;\sim  N(\mu_{ij}, \sigma^2_{Reaction}) \\ 
\mu_{ij} &amp;= \beta_0 + \beta_1 Subject_{ij} + b_{0i} + b_{1i} Subject_{ij} \\
\left (
\begin{matrix}
b_{0} \\ b_{1}
\end{matrix} 
\right ) &amp;\sim 
N\left ( \left [ \begin{matrix}
0 \\ 0
\end{matrix} \right ],
\left [ \begin{matrix}
\sigma^2_{b0} &amp; \sigma_{b01} \\ 
\sigma_{b01} &amp; \sigma^2_{b1}
\end{matrix} \right ]
\right )
\end{align*}\]</span></p>
<p>Aquí, los individuos (<span class="math inline">\(i\)</span>) varían en el tiempo de reacción promedio tanto en su intercepto (<span class="math inline">\(b_{0i}\)</span>) como en su pendiente (<span class="math inline">\(b_{1i}\)</span>), que en conjunto componen la varianza total en dicho tiempo atribuible a la variación entre individuos. Esta contribución individual se cuantifica usando un modelo de intercepto y pendiente aleatoria con distribución normal (<span class="math inline">\(N\)</span>). La variación entre individuos en intercepto y pendiente es <span class="math inline">\(\sigma^2_{b0}\)</span> y <span class="math inline">\(\sigma²_{b1}\)</span>, respectivamente. La covarianza entre el intercepto y la pendiente esta dada por <span class="math inline">\(\sigma_{b01}\)</span>.</p>
<p>El vector de parámetros para este modelo sería <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0, \beta_1, \sigma_y, \sigma_{b0}, \sigma_{b1}, \sigma_{b0b1})^\top\)</span>.</p>
<p>Para ajustar el modelo de intercepto y pendiente aleatoria planteado usando el paquete <code>lme4</code> podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">fit &lt;-<span class="st"> </span><span class="kw">lmer</span>(Reaction <span class="op">~</span><span class="st"> </span>Days <span class="op">+</span><span class="st"> </span>(Days <span class="op">|</span><span class="st"> </span>Subject), <span class="dt">REML =</span> <span class="ot">TRUE</span>, <span class="dt">data =</span> sleepstudy)</a></code></pre></div>
<p>Para obtener la tabla de resumen usamos:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">summary</span>(fit)</a></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Reaction ~ Days + (Days | Subject)
##    Data: sleepstudy
## 
## REML criterion at convergence: 1743.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.9536 -0.4634  0.0231  0.4633  5.1793 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  Subject  (Intercept) 611.90   24.737       
##           Days         35.08    5.923   0.07
##  Residual             654.94   25.592       
## Number of obs: 180, groups:  Subject, 18
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  251.405      6.824  36.843
## Days          10.467      1.546   6.771
## 
## Correlation of Fixed Effects:
##      (Intr)
## Days -0.138</code></pre>
<p>De la salida anterior se obtienen los siguientes parámetros (<span class="math inline">\(\Theta\)</span>):</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
<span class="math inline">\(\Theta\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\beta_{0}\)</span>
</td>
<td style="text-align:right;">
251.40
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\beta_{1}\)</span>
</td>
<td style="text-align:right;">
10.47
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sigma_{y}\)</span>
</td>
<td style="text-align:right;">
25.59
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sigma_{b0}\)</span>
</td>
<td style="text-align:right;">
24.74
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sigma_{b1}\)</span>
</td>
<td style="text-align:right;">
5.92
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sigma_{b0b1}\)</span>
</td>
<td style="text-align:right;">
10.25
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>*</sup> El útimo parámetro estimado se obtiene utilizando la ecuación<br> de <a href="https://en.wikipedia.org/wiki/Correlation_and_dependence">correlación</a> que relaciona la covarianza y desviaciones de los<br> efectos aleatorios: <span class="math inline">\(Cor=Cov/(\sigma_1 * \sigma_2)\)</span>.
</td>
</tr>
</tfoot>
</table>
<p>Usando la información anterior se puede escribir el modelo ajustado de la siguiente manera:</p>
<p><span class="math display">\[\begin{align*} 
Reaction_{ij} &amp;\sim  N(\hat{\mu}_{ij}, 25.59^2) \\ 
\hat{\mu}_{ij} &amp;= 251.40 + 10.47 Subject_{ij} + b_{0i} + b_{1i} Subject_{ij} \\
\left (
\begin{matrix}
b_{0} \\ b_{1}
\end{matrix} 
\right ) &amp;\sim 
N\left ( \left [ \begin{matrix}
0 \\ 0
\end{matrix} \right ],
\left [ \begin{matrix}
24.74^2 &amp; 10.25 \\ 
10.25 &amp; 5.92^2
\end{matrix} \right ]
\right ).
\end{align*}\]</span></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="references.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_modelos_mixtos/edit/master/apli-lme4.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
