<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>28 Intervalos de confianza | Modelos Mixtos con R</title>
  <meta name="description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="28 Intervalos de confianza | Modelos Mixtos con R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="28 Intervalos de confianza | Modelos Mixtos con R" />
  
  <meta name="twitter:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández Barajas" />
<meta name="author" content="Jorge Leonardo López Martínez" />


<meta name="date" content="2026-02-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="R2.html"/>
<link rel="next" href="simul-glmm.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Mixtos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#la-complejidad-estructural-tenida-en-cuenta-por-los-modelos-mixtos"><i class="fa fa-check"></i><b>1.1</b> La complejidad estructural tenida en cuenta por los modelos mixtos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reg-lin.html"><a href="reg-lin.html"><i class="fa fa-check"></i><b>2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="702-IC.html"><a href="#modelo-estad%C3%ADstico"><i class="fa fa-check"></i><b>2.1</b> Modelo estadístico</a></li>
<li class="chapter" data-level="2.2" data-path="reg-lin.html"><a href="reg-lin.html#verosimilitud-del-modelo"><i class="fa fa-check"></i><b>2.2</b> Verosimilitud del modelo</a>
<ul>
<li class="chapter" data-level="" data-path="reg-lin.html"><a href="reg-lin.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lmm.html"><a href="lmm.html"><i class="fa fa-check"></i><b>3</b> Modelos Lineales Mixtos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lmm.html"><a href="lmm.html#entrevista-con-jim-ware-y-nan-laird"><i class="fa fa-check"></i><b>3.1</b> Entrevista con Jim Ware y Nan Laird</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>4</b> Aplicaciones shiny</a></li>
<li class="chapter" data-level="5" data-path="pac-lme4.html"><a href="pac-lme4.html"><i class="fa fa-check"></i><b>5</b> Paquete <strong>lme4</strong></a>
<ul>
<li class="chapter" data-level="5.1" data-path="702-IC.html"><a href="#funci%C3%B3n-lmer"><i class="fa fa-check"></i><b>5.1</b> Función <code>lmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-normal-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-recuperando-los-interceptos-aleatorios"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="5.2" data-path="702-IC.html"><a href="#funci%C3%B3n-glmer"><i class="fa fa-check"></i><b>5.2</b> Función <code>glmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-gamma-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-inversa-gaussiana-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i>Ejemplo: modelo inversa gaussiana con intercepto y pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="apli-lme4.html"><a href="apli-lme4.html"><i class="fa fa-check"></i><b>6</b> Aplicación con <code>lme4</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-lme4.html"><a href="apli-lme4.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="pac-nlme.html"><a href="pac-nlme.html"><i class="fa fa-check"></i><b>7</b> Paquete <strong>nlme</strong></a>
<ul>
<li class="chapter" data-level="7.1" data-path="702-IC.html"><a href="#funci%C3%B3n-lme"><i class="fa fa-check"></i><b>7.1</b> Función <code>lme</code></a></li>
<li class="chapter" data-level="" data-path="pac-nlme.html"><a href="pac-nlme.html#ejemplo-modelo-normal-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apli-nlme.html"><a href="apli-nlme.html"><i class="fa fa-check"></i><b>8</b> Aplicación con <code>nlme</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-nlme.html"><a href="apli-nlme.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="apli-rat-pup.html"><a href="apli-rat-pup.html"><i class="fa fa-check"></i><b>9</b> Aplicación rat pup</a></li>
<li class="chapter" data-level="10" data-path="estim.html"><a href="estim.html"><i class="fa fa-check"></i><b>10</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estim.html"><a href="estim.html#ml-y-reml"><i class="fa fa-check"></i><b>10.1</b> ML y REML</a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-lme4"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>lme4</strong></a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-nlme"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>nlme</strong></a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejercicios-2"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>11</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="702-IC.html"><a href="#prueba-raz%C3%B3n-de-verosimilitud"><i class="fa fa-check"></i><b>11.1</b> Prueba razón de verosimilitud</a></li>
<li class="chapter" data-level="11.2" data-path="ph.html"><a href="ph.html#prueba-de-wald"><i class="fa fa-check"></i><b>11.2</b> Prueba de Wald</a></li>
<li class="chapter" data-level="11.3" data-path="702-IC.html"><a href="#prueba-de-hip%C3%B3tesis-sobre-los-efectos-fijos"><i class="fa fa-check"></i><b>11.3</b> Prueba de hipótesis sobre los efectos fijos</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="702-IC.html"><a href="#prueba-de-hip%C3%B3tesis-sobre-componentes-de-varianza"><i class="fa fa-check"></i><b>11.4</b> Prueba de hipótesis sobre componentes de varianza</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="ph.html"><a href="ph.html#componentes-de-varianza-lejos-del-borde"><i class="fa fa-check"></i><b>11.4.1</b> Componentes de varianza lejos del borde</a></li>
<li class="chapter" data-level="11.4.2" data-path="ph.html"><a href="ph.html#componentes-de-varianza-en-el-borde"><i class="fa fa-check"></i><b>11.4.2</b> Componentes de varianza en el borde</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejercicios-3"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="var-fun.html"><a href="var-fun.html"><i class="fa fa-check"></i><b>12</b> Modelando la heterocedasticidad</a>
<ul>
<li class="chapter" data-level="12.1" data-path="var-fun.html"><a href="var-fun.html#opciones-para-modelar-la-varianza"><i class="fa fa-check"></i><b>12.1</b> Opciones para modelar la varianza</a></li>
<li class="chapter" data-level="12.2" data-path="var-fun.html"><a href="var-fun.html#varfixed"><i class="fa fa-check"></i><b>12.2</b> varFixed</a></li>
<li class="chapter" data-level="" data-path="var-fun.html"><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cuantitativa"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cuantitativa</a></li>
<li class="chapter" data-level="12.3" data-path="var-fun.html"><a href="var-fun.html#varident"><i class="fa fa-check"></i><b>12.3</b> varIdent</a></li>
<li class="chapter" data-level="" data-path="var-fun.html"><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cualitativa"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cualitativa</a></li>
<li class="chapter" data-level="12.4" data-path="var-fun.html"><a href="var-fun.html#varexp"><i class="fa fa-check"></i><b>12.4</b> varExp</a></li>
<li class="chapter" data-level="" data-path="var-fun.html"><a href="var-fun.html#ejemplo-sigma2_y-con-estructura-exponencial"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> con estructura exponencial</a></li>
<li class="chapter" data-level="12.5" data-path="var-fun.html"><a href="var-fun.html#varconstpower"><i class="fa fa-check"></i><b>12.5</b> varConstPower</a></li>
<li class="chapter" data-level="" data-path=""><a href="#ejemplo-sigma_y2-dependiendo-de-una-variable-constante-m%C3%A1s-la-potencia-de-una-variable-cuantitativa"><i class="fa fa-check"></i>Ejemplo: <span class="math inline">\(\sigma_y^2\)</span> dependiendo de una variable constante más la potencia de una variable cuantitativa</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="more-levels.html"><a href="more-levels.html"><i class="fa fa-check"></i><b>13</b> Modelos con más de dos niveles</a></li>
<li class="chapter" data-level="14" data-path="marginals-effects.html"><a href="marginals-effects.html"><i class="fa fa-check"></i><b>14</b> Paquete <strong>marginaleffects</strong></a>
<ul>
<li class="chapter" data-level="" data-path="marginals-effects.html"><a href="marginals-effects.html#ejemplo-chickweight-lineal"><i class="fa fa-check"></i>Ejemplo ChickWeight lineal</a></li>
<li class="chapter" data-level="" data-path=""><a href="#ejemplo-chickweight-cuadr%C3%A1tico"><i class="fa fa-check"></i>Ejemplo ChickWeight cuadrático</a></li>
<li class="chapter" data-level="14.1" data-path="marginals-effects.html"><a href="marginals-effects.html#ejemplo-5"><i class="fa fa-check"></i><b>14.1</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ggeffects.html"><a href="ggeffects.html"><i class="fa fa-check"></i><b>15</b> Paquete <strong>ggeffects</strong></a></li>
<li class="chapter" data-level="16" data-path="predict-new.html"><a href="predict-new.html"><i class="fa fa-check"></i><b>16</b> Predicción</a></li>
<li class="chapter" data-level="17" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>17</b> Modelos Lineales Generalizados Mixtos</a>
<ul>
<li class="chapter" data-level="17.1" data-path="glmm.html"><a href="glmm.html#videos-de-apoyo"><i class="fa fa-check"></i><b>17.1</b> Videos de apoyo</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html"><i class="fa fa-check"></i><b>18</b> Paquete <strong>glmmTMB</strong></a>
<ul>
<li class="chapter" data-level="18.1" data-path="702-IC.html"><a href="#funci%C3%B3n-glmmtmb"><i class="fa fa-check"></i><b>18.1</b> Función <code>glmmTMB</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-normal-con-intercepto-aleatorio-2"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-recuperando-los-interceptos-aleatorios-1"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-gamma-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="pac-glmm.html"><a href="pac-glmm.html"><i class="fa fa-check"></i><b>19</b> Paquete <strong>glmm</strong></a>
<ul>
<li class="chapter" data-level="19.1" data-path="702-IC.html"><a href="#funci%C3%B3n-glmm"><i class="fa fa-check"></i><b>19.1</b> Función <code>glmm</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmm.html"><a href="pac-glmm.html#ejemplo-modelo-poisson-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Poisson con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="pac-MASS.html"><a href="pac-MASS.html"><i class="fa fa-check"></i><b>20</b> Paquete <strong>MASS</strong></a>
<ul>
<li class="chapter" data-level="20.1" data-path="702-IC.html"><a href="#funci%C3%B3n-glmmpql"><i class="fa fa-check"></i><b>20.1</b> Función <code>glmmPQL</code></a></li>
<li class="chapter" data-level="" data-path="pac-MASS.html"><a href="pac-MASS.html#ejemplo-modelo-bernoulli-binomial-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Bernoulli (binomial) con intercepto aleatorio</a></li>
<li class="chapter" data-level="20.2" data-path="pac-MASS.html"><a href="pac-MASS.html#what-it-means-for-aic-na-in-glmmpql-mass-summary-output"><i class="fa fa-check"></i><b>20.2</b> What it means for AIC NA in glmmPQL (MASS) summary output?</a></li>
<li class="chapter" data-level="20.3" data-path="pac-MASS.html"><a href="pac-MASS.html#two-questions-on-the-results-from-glmmpqlmass"><i class="fa fa-check"></i><b>20.3</b> Two questions on the results from glmmPQL(MASS)</a></li>
<li class="chapter" data-level="20.4" data-path="pac-MASS.html"><a href="pac-MASS.html#how-do-i-interpret-the-variance-of-random-effect-in-a-generalized-linear-mixed-model"><i class="fa fa-check"></i><b>20.4</b> How do I interpret the variance of random effect in a generalized linear mixed model?</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="paquete-inla.html"><a href="paquete-inla.html"><i class="fa fa-check"></i><b>21</b> Paquete <strong>INLA</strong></a>
<ul>
<li class="chapter" data-level="" data-path="paquete-inla.html"><a href="paquete-inla.html#ejemplo-modelo-poisson-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo Poisson con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="paquete-inla.html"><a href="paquete-inla.html#ejemplo-modelo-poisson-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i>Ejemplo: modelo Poisson con intercepto y pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html"><i class="fa fa-check"></i><b>22</b> Paquete <strong>gamlss</strong></a>
<ul>
<li class="chapter" data-level="22.1" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#modelo-lineal-mixto-con-intercepto-aleatorio"><i class="fa fa-check"></i><b>22.1</b> Modelo lineal mixto con intercepto aleatorio</a>
<ul>
<li class="chapter" data-level="" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#modelo-lineal-mixto-con-pendiente-aleatoria"><i class="fa fa-check"></i><b>22.2</b> Modelo lineal mixto con pendiente aleatoria</a>
<ul>
<li class="chapter" data-level="" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#modelo-lineal-mixto-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i><b>22.3</b> Modelo lineal mixto con intercepto y pendiente aleatoria</a>
<ul>
<li class="chapter" data-level="" data-path="paquete-gamlss.html"><a href="paquete-gamlss.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="glmm_poisson.html"><a href="glmm_poisson.html"><i class="fa fa-check"></i><b>23</b> GLMM Poisson</a></li>
<li class="chapter" data-level="24" data-path="glmm-gamma.html"><a href="glmm-gamma.html"><i class="fa fa-check"></i><b>24</b> GLMM gamma</a></li>
<li class="chapter" data-level="25" data-path="multinomial.html"><a href="multinomial.html"><i class="fa fa-check"></i><b>25</b> Modelo multinomial</a>
<ul>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-modelo-multinomial-nominal"><i class="fa fa-check"></i>Ejemplo: modelo multinomial nominal</a></li>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-modelo-multinomial-ordinal"><i class="fa fa-check"></i>Ejemplo: modelo multinomial ordinal</a></li>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-simulando-observaciones-de-un-modelo-multinomial-nominal"><i class="fa fa-check"></i>Ejemplo: simulando observaciones de un modelo multinomial nominal</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="residuals.html"><a href="residuals.html"><i class="fa fa-check"></i><b>26</b> Diagnósticos con DHARMa</a>
<ul>
<li class="chapter" data-level="" data-path="residuals.html"><a href="residuals.html#ejemplo-modelo-gamma-mixto"><i class="fa fa-check"></i>Ejemplo: modelo gamma mixto</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="R2.html"><a href="R2.html"><i class="fa fa-check"></i><b>27</b> Coeficiente <span class="math inline">\(R^2\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="R2.html"><a href="R2.html#ejemplo-modelo-normal-con-intercepto-aleatorio-3"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="R2.html"><a href="R2.html#ejemplo-modelo-normal-sin-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo normal sin intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="R2.html"><a href="R2.html#ejemplo-modelo-clase-lme"><i class="fa fa-check"></i>Ejemplo: modelo clase lme</a></li>
<li class="chapter" data-level="" data-path="R2.html"><a href="R2.html#ejemplo-modelo-clase-lme4"><i class="fa fa-check"></i>Ejemplo: modelo clase lme4</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="IC.html"><a href="IC.html"><i class="fa fa-check"></i><b>28</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="28.1" data-path="702-IC.html"><a href="#intervalos-de-confianza-para-los-par%C3%A1metros"><i class="fa fa-check"></i><b>28.1</b> Intervalos de confianza para los parámetros</a></li>
<li class="chapter" data-level="" data-path="IC.html"><a href="IC.html#ejemplo-modelo-normal"><i class="fa fa-check"></i>Ejemplo: modelo normal</a></li>
<li class="chapter" data-level="" data-path="IC.html"><a href="IC.html#ejemplo-modelo-gamma"><i class="fa fa-check"></i>Ejemplo: modelo gamma</a></li>
<li class="chapter" data-level="28.2" data-path="702-IC.html"><a href="#intervalos-de-confianza-para-predicci%C3%B3n"><i class="fa fa-check"></i><b>28.2</b> Intervalos de confianza para predicción</a></li>
<li class="chapter" data-level="" data-path="IC.html"><a href="IC.html#ejemplo-modelo-normal-1"><i class="fa fa-check"></i>Ejemplo: modelo normal</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="simul-glmm.html"><a href="simul-glmm.html"><i class="fa fa-check"></i><b>29</b> Simulación de glmm</a>
<ul>
<li class="chapter" data-level="29.1" data-path="simul-glmm.html"><a href="simul-glmm.html#ejemplo-para-datos-de-crecimiento"><i class="fa fa-check"></i><b>29.1</b> Ejemplo para datos de crecimiento</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="sced.html"><a href="sced.html"><i class="fa fa-check"></i><b>30</b> Single case experimental desing (sced)</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#ejemplo-simulaci%C3%B3n-de-un-sced-abab"><i class="fa fa-check"></i>Ejemplo: simulación de un sced ABAB</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="blobs.html"><a href="blobs.html"><i class="fa fa-check"></i><b>31</b> Otro material interesante</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Mixtos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="IC" class="section level1 hasAnchor" number="28">
<h1><span class="header-section-number">28</span> Intervalos de confianza<a href="IC.html#IC" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo vamos mostrar como se pueden obtener intervalos de confianza para los parámetros del modelo e intervalos de confianza para predicción.</p>
<div id="intervalos-de-confianza-para-los-parámetros" class="section level2 hasAnchor" number="28.1">
<h2><span class="header-section-number">28.1</span> Intervalos de confianza para los parámetros<a href="#intervalos-de-confianza-para-los-par%C3%A1metros" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se mostrará cómo utilizar la función <code>confint()</code> para obtener intervalos de confianza para los elementos del vector de parámetros <span class="math inline">\(\boldsymbol{\Theta}\)</span> de un modelo lineal generalizado mixto.</p>
</div>
<div id="ejemplo-modelo-normal" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: modelo normal<a href="IC.html#ejemplo-modelo-normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este ejemplo su usará la base de datos <code>sleepstudy</code> del paquete <code>lme4</code> sobre el tiempo de reacción promedio por día para un conjunto de individuos en un estudio de privación del sueño. La base de datos contiene la información sobre el tiempo de reacción promedio (<code>Reaction</code>), el número de días de privación del sueño (<code>Days</code>), donde el día 0 corresponde al día en el que los indiviuos tenían su cantidad normal de sueño, y el número del individuo (en total 18) sobre el que se realizó la observación (<code>Subject</code>). A partir del día 0, hubo una restricción en cada individuo a 3 horas de sueño por noche.</p>
<p><img src="images/sleep_study.png" width="40%" style="display: block; margin: auto;" /></p>
<p>El objetivo es ajustar el siguiente modelo a los datos.</p>
<p><span class="math display">\[\begin{align*}
Reaction_{ij} | b_0, b_1 &amp;\sim  N(\mu_{ij}, \sigma^2_{Reaction}) \\
\mu_{ij} &amp;= \beta_0 + \beta_1 Days_{ij} + b_{0i} + b_{1i} Days_{ij} \\
\left (
\begin{matrix}
b_{0} \\ b_{1}
\end{matrix}
\right ) &amp;\sim
N\left ( \left [ \begin{matrix}
0 \\ 0
\end{matrix} \right ],
\left [ \begin{matrix}
\sigma^2_{b0} &amp; \sigma_{b01} \\
\sigma_{b01} &amp; \sigma^2_{b1}
\end{matrix} \right ]
\right )
\end{align*}\]</span></p>
<p>Lo primero que debemos hacer es ajustar el modelo usando el siguiente código.</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="IC.html#cb391-1" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb391-2"><a href="IC.html#cb391-2" tabindex="-1"></a><span class="fu">head</span>(sleepstudy)</span></code></pre></div>
<pre><code>##   Reaction Days Subject pred_inter_pend_aleatorio modelo_simple
## 1 249.5600    0     308                  253.6637      251.4051
## 2 258.7047    1     308                  273.3299      261.8724
## 3 250.8006    2     308                  292.9962      272.3397
## 4 321.4398    3     308                  312.6624      282.8070
## 5 356.8519    4     308                  332.3287      293.2742
## 6 414.6901    5     308                  351.9950      303.7415
##   pred_inter_aleatorio pred_pend_aleatorio
## 1             292.1888            251.4051
## 2             302.6561            271.4918
## 3             313.1234            291.5785
## 4             323.5907            311.6652
## 5             334.0580            331.7519
## 6             344.5252            351.8386</code></pre>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="IC.html#cb393-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">|</span> Subject), <span class="at">REML =</span> <span class="cn">TRUE</span>, <span class="at">data =</span> sleepstudy)</span></code></pre></div>
<p>La tabla de resultados del modelo ajustado se muestra a continuación.</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="IC.html#cb394-1" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Reaction ~ Days + (Days | Subject)
##    Data: sleepstudy
## 
## REML criterion at convergence: 1743.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.9536 -0.4634  0.0231  0.4634  5.1793 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  Subject  (Intercept) 612.10   24.741       
##           Days         35.07    5.922   0.07
##  Residual             654.94   25.592       
## Number of obs: 180, groups:  Subject, 18
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  251.405      6.825  36.838
## Days          10.467      1.546   6.771
## 
## Correlation of Fixed Effects:
##      (Intr)
## Days -0.138</code></pre>
<p>De la tabla anterior podemos ver que las estimaciones del vector de parámetros es</p>
<p><span class="math display">\[
\hat{\boldsymbol{\Theta}} = (\hat{\beta_0}=251.40, \hat{\beta_1}=10.47, \hat{\sigma}_{reaction}=25.59, \hat{\sigma}_{b0}=24.74, \hat{\sigma}_{b1}=5.92, \hat{\rho}_{b0b1}=0.07)^\top
\]</span></p>
<p>Para obtener los intervalos de confianza podemos usar la función <code>confint()</code> al objeto <code>fit</code>.</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="IC.html#cb396-1" tabindex="-1"></a><span class="do">#### Calculate Wald CIs (Fastest Version) ####</span></span>
<span id="cb396-2"><a href="IC.html#cb396-2" tabindex="-1"></a>ci.wald <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="at">level=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## Computing profile confidence intervals ...</code></pre>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="IC.html#cb398-1" tabindex="-1"></a>ci.wald</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## .sig01       14.3814379  37.7159918
## .sig02       -0.4815008   0.6849863
## .sig03        3.8011643   8.7533658
## .sigma       22.8982669  28.8579965
## (Intercept) 237.6806955 265.1295145
## Days          7.3586533  13.5759188</code></pre>
<p>También es posible obtener los intervalos de confianza por el método boostrap así.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="IC.html#cb400-1" tabindex="-1"></a><span class="do">#### Calculate Bootstrapped CIs ####</span></span>
<span id="cb400-2"><a href="IC.html#cb400-2" tabindex="-1"></a>ci.boot <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="at">method =</span> <span class="st">&quot;boot&quot;</span>, <span class="at">nsim =</span> <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>## 
## 11 message(s): boundary (singular) fit: see help(&#39;isSingular&#39;)
## 7 warning(s): Model failed to converge with max|grad| = 0.00237033 (tol = 0.002, component 1) (and others)</code></pre>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="IC.html#cb403-1" tabindex="-1"></a>ci.boot</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## .sig01       12.9637679  35.9428046
## .sig02       -0.5360978   0.8664981
## .sig03        3.1342841   8.4724073
## .sigma       22.6178539  28.5395275
## (Intercept) 237.7970463 265.0299430
## Days          7.3768799  13.7273663</code></pre>
</div>
<div id="ejemplo-modelo-gamma" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: modelo gamma<a href="IC.html#ejemplo-modelo-gamma" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este ejemplo analizamos los datos de semiconductores tomados de Myers et al. (2002) sobre un experimento diseñado en una planta de semiconductores. Se emplean seis factores, temperatura de laminación, tiempo de laminación, presión de laminación, temperatura de cocción, tiempo de ciclo de cocción y punto de rocío de cocción, y estamos interesados en la curvatura de los dispositivos de sustrato producidos en la planta. La medición de la curvatura se realiza cuatro veces en cada dispositivo fabricado. Cada variable de diseño se toma en dos niveles. Se sabe que la medida no tiene una distribución normal y las medidas tomadas en el mismo dispositivo están correlacionadas.</p>
<p>Las variables de la base de datos se muestran a continuación.</p>
<ul>
<li>Device: Subtrate device</li>
<li>x1: Lamination Temperature; two levels +1 and -1.</li>
<li>x2: Lamination Time; two levels: +1 and -1.</li>
<li>x3: Lamination Presure; two levels: +1 and -1.</li>
<li>x4: Firing Temperature; two levels: +1 and -1.</li>
<li>x5: Firing Cycle Time; two levels: +1 and -1.</li>
<li>x6: Firing Dew Point: two levels: +1 and -1.</li>
<li>y: Camber measure; in 1e-4 in./in.</li>
</ul>
<p><img src="images/semiconductors.jpg" alt="Tomada de https://www.iqsdirectory.com/" width="50%" style="display: block; margin: auto;" /></p>
<p>El objetivo es ajustar el siguiente modelo a los datos.</p>
<p><span class="math display">\[\begin{align*}
y_{ij} | b_0 &amp;\sim  Gamma(\mu_{ij}, \phi) \\
\log(\mu_{ij}) &amp;= \beta_0 + \beta_1 x1_{ij} + \beta_3 x3_{ij} + \beta_5 x5_{ij} + \beta_6 x6_{ij} + b_{0i} \\
b_{0} &amp;\sim N(0, \sigma^2_{b0})
\end{align*}\]</span></p>
<p>Para ajustar el modelo anterior usamos el siguiente código.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="IC.html#cb405-1" tabindex="-1"></a><span class="fu">library</span>(hglm)</span>
<span id="cb405-2"><a href="IC.html#cb405-2" tabindex="-1"></a><span class="fu">data</span>(semiconductor)</span>
<span id="cb405-3"><a href="IC.html#cb405-3" tabindex="-1"></a></span>
<span id="cb405-4"><a href="IC.html#cb405-4" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb405-5"><a href="IC.html#cb405-5" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x3 <span class="sc">+</span> x5 <span class="sc">+</span> x6 <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Device), </span>
<span id="cb405-6"><a href="IC.html#cb405-6" tabindex="-1"></a>               <span class="at">data =</span> semiconductor,</span>
<span id="cb405-7"><a href="IC.html#cb405-7" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link =</span> log))</span>
<span id="cb405-8"><a href="IC.html#cb405-8" tabindex="-1"></a></span>
<span id="cb405-9"><a href="IC.html#cb405-9" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>##  Family: Gamma  ( log )
## Formula:          y ~ x1 + x3 + x5 + x6 + (1 | Device)
## Data: semiconductor
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    -545.2    -530.1     279.6    -559.2        57 
## 
## Random effects:
## 
## Conditional model:
##  Groups Name        Variance Std.Dev.
##  Device (Intercept) 0.02505  0.1583  
## Number of obs: 64, groups:  Device, 16
## 
## Dispersion estimate for Gamma family (sigma^2): 0.101 
## 
## Conditional model:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.69447    0.05635  -83.31  &lt; 2e-16 ***
## x1           0.18290    0.05629    3.25 0.001158 ** 
## x3           0.30496    0.05629    5.42 6.04e-08 ***
## x5          -0.19565    0.05632   -3.47 0.000513 ***
## x6          -0.36961    0.05630   -6.57 5.19e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De la tabla anterior podemos ver que las estimaciones del vector de parámetros es</p>
<p><span class="math display">\[
\hat{\boldsymbol{\Theta}} = (\hat{\beta_0}=-4.71, \hat{\beta_1}=0.18, \hat{\beta_3}=0.31, \hat{\beta_5}=-0.19, \hat{\beta_6}=-0.37, \hat{\phi}=0.31, \hat{\sigma}_{b0}=0.17)^\top
\]</span></p>
<p>Para obtener los intervalos de confianza podemos usar la función <code>confint()</code> al objeto <code>fit</code>.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="IC.html#cb407-1" tabindex="-1"></a>FUN <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">model=</span>fit) {</span>
<span id="cb407-2"><a href="IC.html#cb407-2" tabindex="-1"></a>  fm1R <span class="ot">&lt;-</span> <span class="fu">refit</span>(fit, <span class="fu">simulate</span>(fit)[[<span class="dv">1</span>]])</span>
<span id="cb407-3"><a href="IC.html#cb407-3" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">as.numeric</span>(fm1R<span class="sc">$</span>fit<span class="sc">$</span>par[<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>]),</span>
<span id="cb407-4"><a href="IC.html#cb407-4" tabindex="-1"></a>              fm1R<span class="sc">$</span>obj<span class="sc">$</span><span class="fu">report</span>()<span class="sc">$</span>sd[[<span class="dv">1</span>]])</span>
<span id="cb407-5"><a href="IC.html#cb407-5" tabindex="-1"></a>  <span class="fu">return</span>(result)</span>
<span id="cb407-6"><a href="IC.html#cb407-6" tabindex="-1"></a>}</span>
<span id="cb407-7"><a href="IC.html#cb407-7" tabindex="-1"></a></span>
<span id="cb407-8"><a href="IC.html#cb407-8" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">bootMer</span>(fit, FUN, <span class="at">nsim=</span><span class="dv">30</span>, <span class="at">.progress=</span><span class="st">&quot;txt&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="IC.html#cb408-1" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">requireNamespace</span>(<span class="st">&quot;boot&quot;</span>)) {</span>
<span id="cb408-2"><a href="IC.html#cb408-2" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;95% Bootstrap confidence intervals for glmmTMB</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb408-3"><a href="IC.html#cb408-3" tabindex="-1"></a>   <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>) {</span>
<span id="cb408-4"><a href="IC.html#cb408-4" tabindex="-1"></a>     <span class="fu">print</span>(<span class="fu">boot.ci</span>(b1, <span class="at">type=</span><span class="st">&quot;perc&quot;</span>, <span class="at">index=</span>i)[<span class="dv">4</span>]<span class="sc">$</span>percent[<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb408-5"><a href="IC.html#cb408-5" tabindex="-1"></a>   }</span>
<span id="cb408-6"><a href="IC.html#cb408-6" tabindex="-1"></a>  }</span></code></pre></div>
</div>
<div id="intervalos-de-confianza-para-predicción" class="section level2 hasAnchor" number="28.2">
<h2><span class="header-section-number">28.2</span> Intervalos de confianza para predicción<a href="#intervalos-de-confianza-para-predicci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se mostrará cómo utilizar el paquete <code>ggeffects</code> para obtener intervalos de confianza para predicciones de un modelo lineal generalizado mixto.</p>
</div>
<div id="ejemplo-modelo-normal-1" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: modelo normal<a href="IC.html#ejemplo-modelo-normal-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este ejemplo vamos a retomar los datos <code>sleepstudy</code> del paquete <code>lme4</code> sobre el tiempo de reacción promedio por día para un conjunto de individuos en un estudio de privación del sueño. La base de datos contiene la información sobre el tiempo de reacción promedio (<code>Reaction</code>), el número de días de privación del sueño (<code>Days</code>), donde el día 0 corresponde al día en el que los indiviuos tenían su cantidad normal de sueño, y el número del individuo (en total 18) sobre el que se realizó la observación (<code>Subject</code>). A partir del día 0, hubo una restricción en cada individuo a 3 horas de sueño por noche.</p>
<p><img src="images/sleep_study.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Primero vamos a ajustar el modelo de interés.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="IC.html#cb409-1" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb409-2"><a href="IC.html#cb409-2" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb409-3"><a href="IC.html#cb409-3" tabindex="-1"></a><span class="fu">data</span>(sleepstudy)</span>
<span id="cb409-4"><a href="IC.html#cb409-4" tabindex="-1"></a></span>
<span id="cb409-5"><a href="IC.html#cb409-5" tabindex="-1"></a><span class="co"># balanced data set</span></span>
<span id="cb409-6"><a href="IC.html#cb409-6" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">|</span> Subject), <span class="at">data =</span> sleepstudy)</span></code></pre></div>
<p>Efectos condicionales</p>
<p>Ahora supongamos que nos interesa predecir el tiempo de reacción de un paciente típico en los días 1, 5 y 9, y los intervalos de confianza del 95% para la predicción en esos mismos días. Para eso vamos a usar la función <code>predict_response()</code> de la siguiente manera:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="IC.html#cb410-1" tabindex="-1"></a><span class="co"># conditional predictions</span></span>
<span id="cb410-2"><a href="IC.html#cb410-2" tabindex="-1"></a>pred1 <span class="ot">&lt;-</span> <span class="fu">predict_response</span>(fit, <span class="st">&quot;Days [1,5,9]&quot;</span>, <span class="at">margin=</span><span class="st">&quot;mean_mode&quot;</span>)</span>
<span id="cb410-3"><a href="IC.html#cb410-3" tabindex="-1"></a>pred1</span></code></pre></div>
<pre><code>## # Predicted values of Reaction
## 
## Days | Predicted |         95% CI
## ---------------------------------
##    1 |    261.87 | 248.48, 275.27
##    5 |    303.74 | 284.83, 322.65
##    9 |    345.61 | 316.74, 374.48
## 
## Adjusted for:
## * Subject = 0 (population-level)</code></pre>
<p>Es posible representar gráficamente la predicción y los intervalos usando la función genérica <code>plot()</code> sobre el objeto <code>pred1</code> así:</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="IC.html#cb412-1" tabindex="-1"></a><span class="fu">plot</span>(pred1)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-295-1.png" width="672" /></p>
<p>Efectos marginales</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="IC.html#cb413-1" tabindex="-1"></a><span class="co"># average marginal predictions</span></span>
<span id="cb413-2"><a href="IC.html#cb413-2" tabindex="-1"></a>pred2 <span class="ot">&lt;-</span> <span class="fu">predict_response</span>(fit, <span class="st">&quot;Days [1,5,9]&quot;</span>, <span class="at">margin =</span> <span class="st">&quot;empirical&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="IC.html#cb414-1" tabindex="-1"></a><span class="fu">plot</span>(pred2)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-297-1.png" width="672" /></p>
<p>Ver <a href="https://www.andrewheiss.com/blog/2022/11/29/conditional-marginal-marginaleffects/" class="uri">https://www.andrewheiss.com/blog/2022/11/29/conditional-marginal-marginaleffects/</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="R2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="simul-glmm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/fhernanb/libro_modelos_mixtos/edit/master/702-IC.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
