<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>23 Modelo multinomial | Modelos Mixtos con R</title>
  <meta name="description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="23 Modelo multinomial | Modelos Mixtos con R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="23 Modelo multinomial | Modelos Mixtos con R" />
  
  <meta name="twitter:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández Barajas" />
<meta name="author" content="Jorge Leonardo López Martínez" />


<meta name="date" content="2022-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="glmm_gamma.html"/>
<link rel="next" href="residuals.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Mixtos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#la-complejidad-estructural-tenida-en-cuenta-por-los-modelos-mixtos"><i class="fa fa-check"></i><b>1.1</b> La complejidad estructural tenida en cuenta por los modelos mixtos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reg-lin.html"><a href="reg-lin.html"><i class="fa fa-check"></i><b>2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reg-lin.html"><a href="reg-lin.html#modelo-estadístico"><i class="fa fa-check"></i><b>2.1</b> Modelo estadístico</a></li>
<li class="chapter" data-level="2.2" data-path="reg-lin.html"><a href="reg-lin.html#verosimilitud-del-modelo"><i class="fa fa-check"></i><b>2.2</b> Verosimilitud del modelo</a>
<ul>
<li class="chapter" data-level="" data-path="reg-lin.html"><a href="reg-lin.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lmm.html"><a href="lmm.html"><i class="fa fa-check"></i><b>3</b> Modelos Lineales Mixtos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lmm.html"><a href="lmm.html#entrevista-con-jim-ware-y-nan-laird"><i class="fa fa-check"></i><b>3.1</b> Entrevista con Jim Ware y Nan Laird</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>4</b> Aplicaciones shiny</a></li>
<li class="chapter" data-level="5" data-path="pac-lme4.html"><a href="pac-lme4.html"><i class="fa fa-check"></i><b>5</b> Paquete <strong>lme4</strong></a>
<ul>
<li class="chapter" data-level="5.1" data-path="pac-lme4.html"><a href="pac-lme4.html#función-lmer"><i class="fa fa-check"></i><b>5.1</b> Función <code>lmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-normal-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-recuperando-los-interceptos-aleatorios"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="5.2" data-path="pac-lme4.html"><a href="pac-lme4.html#función-glmer"><i class="fa fa-check"></i><b>5.2</b> Función <code>glmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-gamma-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-inversa-gaussiana-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i>Ejemplo: modelo inversa gaussiana con intercepto y pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="apli-lme4.html"><a href="apli-lme4.html"><i class="fa fa-check"></i><b>6</b> Aplicación con <code>lme4</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-lme4.html"><a href="apli-lme4.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="pac-nlme.html"><a href="pac-nlme.html"><i class="fa fa-check"></i><b>7</b> Paquete <strong>nlme</strong></a>
<ul>
<li class="chapter" data-level="7.1" data-path="pac-nlme.html"><a href="pac-nlme.html#función-lme"><i class="fa fa-check"></i><b>7.1</b> Función <code>lme</code></a></li>
<li class="chapter" data-level="" data-path="pac-nlme.html"><a href="pac-nlme.html#ejemplo-modelo-normal-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apli-nlme.html"><a href="apli-nlme.html"><i class="fa fa-check"></i><b>8</b> Aplicación con <code>nlme</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-nlme.html"><a href="apli-nlme.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="apli-rat-pup.html"><a href="apli-rat-pup.html"><i class="fa fa-check"></i><b>9</b> Aplicación rat pup</a></li>
<li class="chapter" data-level="10" data-path="estim.html"><a href="estim.html"><i class="fa fa-check"></i><b>10</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estim.html"><a href="estim.html#ml-y-reml"><i class="fa fa-check"></i><b>10.1</b> ML y REML</a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-lme4"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>lme4</strong></a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-nlme"><i class="fa fa-check"></i>Ejemplo: comparando REML y ML usando <strong>nlme</strong></a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="glmm_poisson.html"><a href="glmm_poisson.html"><i class="fa fa-check"></i><b>21</b> GLMM Poisson</a></li>
<li class="chapter" data-level="22" data-path="glmm_gamma.html"><a href="glmm_gamma.html"><i class="fa fa-check"></i><b>22</b> GLMM gamma</a></li>
<li class="chapter" data-level="23" data-path="multinomial.html"><a href="multinomial.html"><i class="fa fa-check"></i><b>23</b> Modelo multinomial</a>
<ul>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-modelo-multinomial-nominal"><i class="fa fa-check"></i>Ejemplo: modelo multinomial nominal</a></li>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-modelo-multinomial-ordinal"><i class="fa fa-check"></i>Ejemplo: modelo multinomial ordinal</a></li>
<li class="chapter" data-level="" data-path="multinomial.html"><a href="multinomial.html#ejemplo-simulando-observaciones-de-un-modelo-multinomial-nominal"><i class="fa fa-check"></i>Ejemplo: simulando observaciones de un modelo multinomial nominal</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="residuals.html"><a href="residuals.html"><i class="fa fa-check"></i><b>24</b> Diagnósticos con DHARMa</a>
<ul>
<li class="chapter" data-level="" data-path="residuals.html"><a href="residuals.html#ejemplo-modelo-gamma-mixto"><i class="fa fa-check"></i>Ejemplo: modelo gamma mixto</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="simul-glmm.html"><a href="simul-glmm.html"><i class="fa fa-check"></i><b>25</b> Simulación de glmm</a></li>
<li class="chapter" data-level="26" data-path="blobs.html"><a href="blobs.html"><i class="fa fa-check"></i><b>26</b> Otro material interesante</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Mixtos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multinomial" class="section level1 hasAnchor" number="23">
<h1><span class="header-section-number">23</span> Modelo multinomial<a href="multinomial.html#multinomial" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se muestran como ajustar un modelo multinomial (nominal y ordinal) con efectos aleatorios.</p>
<div id="ejemplo-modelo-multinomial-nominal" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: modelo multinomial nominal<a href="multinomial.html#ejemplo-modelo-multinomial-nominal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="images/picts.jpeg" width="60%" style="display: block; margin: auto;" /></p>
<p>Este ejemplo está basado en este <a href="https://ladal.edu.au/regression.html#Mixed-Effects_Multinomial_Regression">tutorial</a>. El objetivo es construir un modelo multinomial nominal para explicar la variable <code>Response</code> que tiene cuatro niveles: BareNoun, NumeralNoun, QuantAdjNoun y QuantNoun. En esta situación los niveles de <code>Response</code> no tienen un orden, por esa razón es que este ejemplo encaja en un modelo multinomial nominal.</p>
<p>Los datos que se van a utilizar en este ejemplo corresponden a un experimento en el cual a un grupo de personas con cierta habilidad de lenguaje (English_Mono, German_Mono, L2_Advanced, L2_Intermediate), se les presentaron diez figuras (<em>Item</em>) y ellos debían identificar si la figura se refería a un sustantivo Bare, Numeral, QuantAdj o Quant. Las diez figuras son una muestra de todas las figuras que se podrían tener para el experimento, por eso se pueden considerar que la figura (<em>Item</em>) puede tener una influencia en la respuesta.</p>
<p>El código para acceder a la base de datos se muestra a continuación.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="multinomial.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para cargar los datos</span></span>
<span id="cb280-2"><a href="multinomial.html#cb280-2" aria-hidden="true" tabindex="-1"></a>pict <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">&quot;https://slcladal.github.io/data/pict.rda&quot;</span>, <span class="st">&quot;rb&quot;</span>))</span>
<span id="cb280-3"><a href="multinomial.html#cb280-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Primeras observaciones de la base de datos</span></span>
<span id="cb280-4"><a href="multinomial.html#cb280-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pict, <span class="at">n=</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##   Id Participant       Group Item     Response Gender Age
## 1  1        G001 German_Mono    1  NumeralNoun   Male  18
## 2  2        G002 German_Mono    3  NumeralNoun   Male  18
## 3  3        G003 German_Mono    4  NumeralNoun   Male  18
## 4  4        G004 German_Mono    6 QuantAdjNoun   Male  18
## 5  5        G005 German_Mono    8  NumeralNoun   Male  18
## 6  6        G006 German_Mono    9 QuantAdjNoun   Male  18</code></pre>
<div style="-moz-box-shadow: 1px 1px 3px 2px #000000;
  -webkit-box-shadow: 1px 1px 3px 2px #000000;
  box-shadow:         1px 1px 3px 2px #000000;">

<div class="rmdexercise">
Solución.
</div>
</div>
<p>Antes de ajustar el modelo vamos a explorar un poco los datos. Vamos a crear tablas de frecuencia para la variable respuesta, las covariables y la variable de agrupación <code>Item</code>.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="multinomial.html#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla para la respuesta</span></span>
<span id="cb282-2"><a href="multinomial.html#cb282-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pict<span class="sc">$</span>Response)</span></code></pre></div>
<pre><code>## 
##     BareNoun  NumeralNoun QuantAdjNoun    QuantNoun 
##          394          510          152           34</code></pre>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="multinomial.html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla para las covariables</span></span>
<span id="cb284-2"><a href="multinomial.html#cb284-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pict<span class="sc">$</span>Gender)</span></code></pre></div>
<pre><code>## 
## Female   Male 
##    740    350</code></pre>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="multinomial.html#cb286-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pict<span class="sc">$</span>Group)</span></code></pre></div>
<pre><code>## 
##    English_Mono     German_Mono     L2_Advanced L2_Intermediate 
##             230             310             340             210</code></pre>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="multinomial.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla para la agrupación</span></span>
<span id="cb288-2"><a href="multinomial.html#cb288-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pict<span class="sc">$</span>Item)</span></code></pre></div>
<pre><code>## 
##   1   3   4   6   8   9  11  12  13  15 
## 109 109 109 109 109 109 109 109 109 109</code></pre>
<p>Vamos a retirar la palabra Noun de las respuestas, de esta manera nos quedará más compacta una tabla que haremos al final.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="multinomial.html#cb290-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb290-2"><a href="multinomial.html#cb290-2" aria-hidden="true" tabindex="-1"></a>pict<span class="sc">$</span>Response <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(<span class="at">string=</span>pict<span class="sc">$</span>Response, </span>
<span id="cb290-3"><a href="multinomial.html#cb290-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">pattern=</span><span class="st">&quot;Noun.*&quot;</span>, </span>
<span id="cb290-4"><a href="multinomial.html#cb290-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">replacement=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb290-5"><a href="multinomial.html#cb290-5" aria-hidden="true" tabindex="-1"></a>pict<span class="sc">$</span>Response <span class="ot">&lt;-</span> <span class="fu">factor</span>(pict<span class="sc">$</span>Response)</span></code></pre></div>
<p>Vamos ahora a crear el modelo multinomial nominal con la ayuda de la función <code>mblogit</code> del paquete <strong>mclogit</strong> de <span class="citation">Elff (<a href="#ref-R-mclogit" role="doc-biblioref">2022</a>)</span>. Las covariables que vamos a utilizar para predecir a <code>Response</code> son <code>Gender</code>, <code>Group</code> y <code>Age</code>. La variable <code>Item</code> se refiere a la figura o fotografía mostrada a los participantes y esta variable se va a utilizar como fuente del intercepto aleatorio <span class="math inline">\(b0\)</span> que se va a incluir en el modelo. El intercepto aleatorio se le indica a <code>mblogit</code> por medio de <code>random = ~ 1 | Item</code>.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="multinomial.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mclogit)</span>
<span id="cb291-2"><a href="multinomial.html#cb291-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">mblogit</span>(<span class="at">formula =</span> Response <span class="sc">~</span> Gender <span class="sc">+</span> Group <span class="sc">+</span> Age, </span>
<span id="cb291-3"><a href="multinomial.html#cb291-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Item, </span>
<span id="cb291-4"><a href="multinomial.html#cb291-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> pict)</span></code></pre></div>
<pre><code>## 
## Iteration 1 - deviance = 1648.607 - criterion = 0.8003659
## Iteration 2 - deviance = 1564.408 - criterion = 0.08391308
## Iteration 3 - deviance = 1544.629 - criterion = 0.02825377
## Iteration 4 - deviance = 1539.952 - criterion = 0.005299121
## Iteration 5 - deviance = 1538.684 - criterion = 0.000183948
## Iteration 6 - deviance = 1538.481 - criterion = 1.807221e-07
## Iteration 7 - deviance = 1538.475 - criterion = 2.534825e-13
## converged</code></pre>
<p>Con el modelo ajustado podemos explorar qué tan bien logra clasificar las observaciones de los datos de entrenamiento. A continuación el código para calcular las probabilidades estimadas <span class="math inline">\(\hat{P}\)</span>, las respuestas estimadas <span class="math inline">\(\widehat{Resp}\)</span> por el modelo, una tabla de confusión tradicional y la tasa de precisión del modelo con los datos de entrenamiento.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="multinomial.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades estimadas para cada nivel de Response</span></span>
<span id="cb293-2"><a href="multinomial.html#cb293-2" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>mod1, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb293-3"><a href="multinomial.html#cb293-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Para identificar el nivel de Response con mayor probabilidad</span></span>
<span id="cb293-4"><a href="multinomial.html#cb293-4" aria-hidden="true" tabindex="-1"></a>aux_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">names</span>(x)[<span class="fu">which.max</span>(x)]</span>
<span id="cb293-5"><a href="multinomial.html#cb293-5" aria-hidden="true" tabindex="-1"></a>Response_hat <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X=</span>probs, <span class="at">MARGIN=</span><span class="dv">1</span>, <span class="at">FUN=</span>aux_fun)</span>
<span id="cb293-6"><a href="multinomial.html#cb293-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de confusion</span></span>
<span id="cb293-7"><a href="multinomial.html#cb293-7" aria-hidden="true" tabindex="-1"></a>Response_hat <span class="ot">&lt;-</span> <span class="fu">factor</span>(Response_hat, <span class="at">levels=</span><span class="fu">levels</span>(pict<span class="sc">$</span>Response))</span>
<span id="cb293-8"><a href="multinomial.html#cb293-8" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">True_Response=</span>pict<span class="sc">$</span>Response, Response_hat)</span>
<span id="cb293-9"><a href="multinomial.html#cb293-9" aria-hidden="true" tabindex="-1"></a>tabla</span></code></pre></div>
<pre><code>##              Response_hat
## True_Response Bare Numeral Quant QuantAdj
##      Bare      308      55     0       31
##      Numeral    78     429     0        3
##      Quant       6      26     0        2
##      QuantAdj   45      37     0       70</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="multinomial.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb295-2"><a href="multinomial.html#cb295-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(tabla)) <span class="sc">/</span> <span class="fu">sum</span>(tabla)</span></code></pre></div>
<pre><code>## [1] 0.740367</code></pre>
<p>Es posible usar el modelo ajustado y la misma función <code>predict</code> para hacer predicciones de la respuesta a items que estén en la base de datos pero con algunos cambios en las covariables. Supongamos que queremos predecir la respuesta nominal para los items 1, 3, 9 y 11 cuando los valores de las covariables son las que se muestran a continuación en el objeto <code>newdata</code>.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="multinomial.html#cb297-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Item=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>, <span class="dv">11</span>)), </span>
<span id="cb297-2"><a href="multinomial.html#cb297-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">Gender=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Male&quot;</span>)),</span>
<span id="cb297-3"><a href="multinomial.html#cb297-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">Group=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;English_Mono&quot;</span>, <span class="st">&quot;Geman_Mono&quot;</span>, <span class="st">&quot;L2_Advanced&quot;</span>, <span class="st">&quot;L2_Intermediate&quot;</span>)),</span>
<span id="cb297-4"><a href="multinomial.html#cb297-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">Age=</span><span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">23</span>, <span class="dv">17</span>))</span>
<span id="cb297-5"><a href="multinomial.html#cb297-5" aria-hidden="true" tabindex="-1"></a>newdata</span></code></pre></div>
<pre><code>##   Item Gender           Group Age
## 1    1   Male    English_Mono  18
## 2    3 Female      Geman_Mono  20
## 3    9 Female     L2_Advanced  23
## 4   11   Male L2_Intermediate  17</code></pre>
<p>Para hacer la predicción usamos la función <code>predict</code> de la siguiente manera.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="multinomial.html#cb299-1" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>mod1, <span class="at">newdata=</span>newdata, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb299-2"><a href="multinomial.html#cb299-2" aria-hidden="true" tabindex="-1"></a>probs</span></code></pre></div>
<pre><code>##            Bare     Numeral       Quant    QuantAdj
## [1,] 0.09863091 0.782680376 0.005847403 0.112841308
## [2,] 0.54910245 0.433187674 0.008833600 0.008876273
## [3,] 0.40685403 0.007197128 0.030881057 0.555067783
## [4,] 0.80135086 0.130020315 0.010356409 0.058272417</code></pre>
<p>En el objeto anterior están las probabilidades de elegir Bare, Numeral, Quant o QuantAdj para los cuatro items. La probabilidad con mayor valor indica la posible elección de cada item. Para extraer la respuesta asociada con la mayor probabilidad podemos hacer lo siguiente.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="multinomial.html#cb301-1" aria-hidden="true" tabindex="-1"></a>aux_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">names</span>(x)[<span class="fu">which.max</span>(x)]</span>
<span id="cb301-2"><a href="multinomial.html#cb301-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(<span class="at">X=</span>probs, <span class="at">MARGIN=</span><span class="dv">1</span>, <span class="at">FUN=</span>aux_fun)</span></code></pre></div>
<pre><code>## [1] &quot;Numeral&quot;  &quot;Bare&quot;     &quot;QuantAdj&quot; &quot;Bare&quot;</code></pre>
<p>De la salida anterior se obtienen las posibles respuestas de cada item cuando los valores de sus covariables son las del objeto <code>newdata</code>.</p>
<div style="-moz-box-shadow: 1px 1px 3px 2px #ffff00;
  -webkit-box-shadow: 1px 1px 3px 2px #ffff00;
  box-shadow:         1px 1px 3px 2px #ffff00;">

<div class="rmdnote">
Cuando se use <code>predict</code> con un nuevo conjunto de datos, debemos asegurarnos de que la estructura del nuevo conjunto de datos coincida con la estructura de los datos de entrenamiento. Es decir, que si usa covariable usad en el modelo es un factor, en el nuevo conjunto de datos debe ser un factor también.
</div>
</div>
</div>
<div id="ejemplo-modelo-multinomial-ordinal" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: modelo multinomial ordinal<a href="multinomial.html#ejemplo-modelo-multinomial-ordinal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="images/insomnia.jpg" width="60%" style="display: block; margin: auto;" /></p>
<p>Este ejemplo fue tomado de la sección 10.3 del libro de <span class="citation">Agresti (<a href="#ref-agresti2018introduction" role="doc-biblioref">2018</a>)</span>. En este ejemplo se analizan los resultados de un ensayo clínico que comparó un fármaco hipnótico activo con un placebo en dos ocasiones en el tratamiento de pacientes con insomnio. La respuesta (hora de conciliar el sueño) cae en una de cuatro categorías ordenadas que son 1 (&lt; 20 min), 2 (20–30 min), 3 (30-60 min) y 4 (&gt; 60 min). Como la respuesta de cada paciente está en una de las cuatro categorías ordenadas, es que se utiliza un modelo multinomial ordinal.</p>
<p>El código para acceder a la base de datos se muestra a continuación.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="multinomial.html#cb303-1" aria-hidden="true" tabindex="-1"></a>Insomnia <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;http://www.stat.ufl.edu/~aa/cat/data/Insomnia.dat&quot;</span>,</span>
<span id="cb303-2"><a href="multinomial.html#cb303-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb303-3"><a href="multinomial.html#cb303-3" aria-hidden="true" tabindex="-1"></a>Insomnia<span class="sc">$</span>response <span class="ot">&lt;-</span> <span class="fu">factor</span>(Insomnia<span class="sc">$</span>response) <span class="co"># response var for clmm must be factor</span></span>
<span id="cb303-4"><a href="multinomial.html#cb303-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Insomnia)</span></code></pre></div>
<pre><code>##   case treat occasion response
## 1    1     1        0        1
## 2    1     1        1        1
## 3    2     1        0        1
## 4    2     1        1        1
## 5    3     1        0        1
## 6    3     1        1        1</code></pre>
<div style="-moz-box-shadow: 1px 1px 3px 2px #000000;
  -webkit-box-shadow: 1px 1px 3px 2px #000000;
  box-shadow:         1px 1px 3px 2px #000000;">

<div class="rmdexercise">
Solución.
</div>
</div>
<p>El modelo de interés en este ejemplo es</p>
<p><span class="math display">\[
\text{logit}[P(Y_{it} \leq j) ] = b0_i + \beta_{0j} + \beta_1 t + \beta_2 x + \beta_3 (t \times x),
\]</span></p>
<p>siendo <span class="math inline">\(i\)</span> el subíndice que identifica a los pacientes <span class="math inline">\(i=1, 2, \ldots, 239\)</span> y <span class="math inline">\(j\)</span> el subíndice que identifica la respuesta ordenada 1, 2, 3 o 4. La variable <span class="math inline">\(t\)</span> se refiere a la ocasión y <span class="math inline">\(x\)</span> al tratamiento. El intercepto aleatorio se denota como <span class="math inline">\(b0\)</span> y el intercepto fijo para cada nivel de <span class="math inline">\(Y\)</span> se denota por <span class="math inline">\(\beta_{0j}\)</span>.</p>
<p>Vamos ahora a crear el modelo multinomial ordinal con la ayuda de la función <code>clmm</code> del paquete <strong>ordinal</strong> de <span class="citation">Christensen (<a href="#ref-R-ordinal" role="doc-biblioref">2019</a>)</span>. Las covariables que vamos a utilizar para predecir a <code>response</code> son <code>occasion</code>, <code>treat</code> y la interacción entre ambas. La variable <code>case</code> se refiere al paciente y esta variable se va a utilizar como fuente del intercepto aleatorio <span class="math inline">\(b0\)</span> que se va a incluir en el modelo. El intercepto aleatorio se le indica a <code>clmm</code> por medio del término <code>(1|case)</code> en la fórmula del modelo.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="multinomial.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span>
<span id="cb305-2"><a href="multinomial.html#cb305-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">clmm</span>(response <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>case) <span class="sc">+</span> occasion <span class="sc">+</span> treat <span class="sc">+</span> occasion<span class="sc">:</span>treat,</span>
<span id="cb305-3"><a href="multinomial.html#cb305-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">nAGQ=</span><span class="dv">20</span>, <span class="at">data=</span>Insomnia) </span>
<span id="cb305-4"><a href="multinomial.html#cb305-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## Cumulative Link Mixed Model fitted with the adaptive Gauss-Hermite 
## quadrature approximation with 20 quadrature points 
## 
## formula: response ~ (1 | case) + occasion + treat + occasion:treat
## data:    Insomnia
## 
##  link  threshold nobs logLik  AIC     niter     max.grad cond.H 
##  logit flexible  478  -592.97 1199.94 401(1549) 1.01e-04 6.1e+01
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  case   (Intercept) 3.628    1.905   
## Number of groups:  case 239 
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## occasion       -1.60158    0.28336  -5.652 1.59e-08 ***
## treat          -0.05785    0.36630  -0.158  0.87450    
## occasion:treat -1.08130    0.38046  -2.842  0.00448 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##     Estimate Std. Error z value
## 1|2  -3.4896     0.3588  -9.727
## 2|3  -1.4846     0.2903  -5.114
## 3|4   0.5613     0.2702   2.078</code></pre>
<p>Los efectos fijos se puden obtener usando la función <code>coef</code>.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="multinomial.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code></pre></div>
<pre><code>##            1|2            2|3            3|4       occasion          treat 
##     -3.4895955     -1.4846367      0.5612784     -1.6015809     -0.0578537 
## occasion:treat 
##     -1.0812951</code></pre>
<p>Los efectos aleatorios se puden obtener usando la función <code>ranef</code>.</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="multinomial.html#cb309-1" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fit)<span class="sc">$</span>case</span></code></pre></div>
<p>Usando la información anterior se puede escribir el modelo ajustado de la siguiente manera:</p>
<p><span class="math display">\[
\text{logit}[P(Y_{it} \leq 1) ] = b0_i -3.49 -1.60 t -0.06 x -1.08 (t \times x),
\]</span>
<span class="math display">\[
\text{logit}[P(Y_{it} \leq 2) ] = b0_i -1.49 -1.60 t -0.06 x -1.08 (t \times x),
\]</span></p>
<p><span class="math display">\[
\text{logit}[P(Y_{it} \leq 3) ] = b0_i + 0.56 -1.60 t -0.06 x -1.08 (t \times x),
\]</span>
El intercepto aleatorio <span class="math inline">\(\tilde{b}0\)</span> predicho está almacenado en el objeto <code>b0</code> y se puede utilizar para completar las expresiones anteriores y así calcular las probabilidades.</p>
</div>
<div id="ejemplo-simulando-observaciones-de-un-modelo-multinomial-nominal" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo: simulando observaciones de un modelo multinomial nominal<a href="multinomial.html#ejemplo-simulando-observaciones-de-un-modelo-multinomial-nominal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este ejemplo vamos a simular observaciones <span class="math inline">\(n_i=50\)</span> observaciones para <span class="math inline">\(G=5\)</span> grupos que tengan la estructura mostrada abajo. El objetivo del ejemplo es ilustrar la forma para estimar los parámetros del modelo.</p>
<p><span class="math display">\[\begin{align*}
y_{ij} | b_0 &amp;\sim  Multinomial(\left\lbrace 1, 2, 3 \right\rbrace, \left\lbrace \pi_1, \pi_2, \pi_3 \right\rbrace) \\
\pi_{1i} &amp;= \frac{e^{1.62-0.11x_{ij}+b0}}{1+e^{1.62-0.11x_{ij}+b0}+e^{5.70.2.47x_{ij}+b0}} \\
\pi_{2i} &amp;= \frac{e^{5.70-2.47x_{ij}+b0}}{1+e^{1.62-0.11x_{ij}+b0}+e^{5.70-2.47x_{ij}+b0}} \\
\pi_{3i} &amp;= \frac{1}{1+e^{1.62-0.11x_{ij}+b0}+e^{5.70-0.2.47x_{ij}+b0}} \\
b_{0} &amp;\sim N(0, \sigma^2_{b0}=4) \\
x_{ij} &amp;\sim U(1, 4)
\end{align*}\]</span></p>
<p>El vector de parámetros de este modelo es <span class="math inline">\(\boldsymbol{\Theta}=(1.62, -0.11, 5.70, -2.47, \sigma_{b0}=2)^\top\)</span>.</p>
<div style="-moz-box-shadow: 1px 1px 3px 2px #000000;
  -webkit-box-shadow: 1px 1px 3px 2px #000000;
  box-shadow:         1px 1px 3px 2px #000000;">

<div class="rmdexercise">
Solución.
</div>
</div>
<p>El código para simular las 500 observaciones se muestra a continuación. Observe que se fijó la semilla en dos ocasiones para que el lector pueda replicar el ejemplo y obtener los mismos resultados.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="multinomial.html#cb310-1" aria-hidden="true" tabindex="-1"></a>ni <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb310-2"><a href="multinomial.html#cb310-2" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb310-3"><a href="multinomial.html#cb310-3" aria-hidden="true" tabindex="-1"></a>nobs <span class="ot">&lt;-</span> ni <span class="sc">*</span> G</span>
<span id="cb310-4"><a href="multinomial.html#cb310-4" aria-hidden="true" tabindex="-1"></a>grupo <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>G, <span class="at">each=</span>ni))</span>
<span id="cb310-5"><a href="multinomial.html#cb310-5" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>ni, <span class="at">times=</span>G)</span>
<span id="cb310-6"><a href="multinomial.html#cb310-6" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>nobs, <span class="at">min=</span><span class="fl">1.2</span>, <span class="at">max=</span><span class="fl">3.9</span>)</span>
<span id="cb310-7"><a href="multinomial.html#cb310-7" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>G, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="fu">sqrt</span>(<span class="dv">0</span>)) <span class="co"># Intercepto aleatorio</span></span>
<span id="cb310-8"><a href="multinomial.html#cb310-8" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span>b0, <span class="at">each=</span>ni)             <span class="co"># El mismo intercepto aleatorio pero repetido</span></span>
<span id="cb310-9"><a href="multinomial.html#cb310-9" aria-hidden="true" tabindex="-1"></a>num1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">1.62-0.11</span><span class="sc">*</span>x<span class="sc">+</span>b0)</span>
<span id="cb310-10"><a href="multinomial.html#cb310-10" aria-hidden="true" tabindex="-1"></a>num2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">5.70-2.47</span><span class="sc">*</span>x<span class="sc">+</span>b0)</span>
<span id="cb310-11"><a href="multinomial.html#cb310-11" aria-hidden="true" tabindex="-1"></a>num3 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb310-12"><a href="multinomial.html#cb310-12" aria-hidden="true" tabindex="-1"></a>den <span class="ot">&lt;-</span> num1 <span class="sc">+</span> num2 <span class="sc">+</span> num3</span>
<span id="cb310-13"><a href="multinomial.html#cb310-13" aria-hidden="true" tabindex="-1"></a>pi1 <span class="ot">&lt;-</span> num1 <span class="sc">/</span> den</span>
<span id="cb310-14"><a href="multinomial.html#cb310-14" aria-hidden="true" tabindex="-1"></a>pi2 <span class="ot">&lt;-</span> num2 <span class="sc">/</span> den</span>
<span id="cb310-15"><a href="multinomial.html#cb310-15" aria-hidden="true" tabindex="-1"></a>pi3 <span class="ot">&lt;-</span> num3 <span class="sc">/</span> den</span>
<span id="cb310-16"><a href="multinomial.html#cb310-16" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pi1, pi2, pi3)</span>
<span id="cb310-17"><a href="multinomial.html#cb310-17" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X=</span>probs, <span class="at">MARGIN=</span><span class="dv">1</span>, which.max)</span>
<span id="cb310-18"><a href="multinomial.html#cb310-18" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">factor</span>(y, <span class="at">levels=</span><span class="dv">3</span><span class="sc">:</span><span class="dv">1</span>)</span>
<span id="cb310-19"><a href="multinomial.html#cb310-19" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(obs, grupo, x, y)</span>
<span id="cb310-20"><a href="multinomial.html#cb310-20" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>y)</span></code></pre></div>
<pre><code>## 
##    3    2    1 
##    0  409 1591</code></pre>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-agresti2018introduction" class="csl-entry">
Agresti, Alan. 2018. <em>An Introduction to Categorical Data Analysis</em>. John Wiley &amp; Sons.
</div>
<div id="ref-R-ordinal" class="csl-entry">
Christensen, Rune Haubo Bojesen. 2019. <em>Ordinal: Regression Models for Ordinal Data</em>. <a href="https://github.com/runehaubo/ordinal">https://github.com/runehaubo/ordinal</a>.
</div>
<div id="ref-R-mclogit" class="csl-entry">
Elff, Martin. 2022. <em>Mclogit: Multinomial Logit Models, with or Without Random Effects or Overdispersion</em>. <a href="https://CRAN.R-project.org/package=mclogit">https://CRAN.R-project.org/package=mclogit</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="glmm_gamma.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="residuals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_modelos_mixtos/edit/master/601-multinomial.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
