<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12 Modelando la heterocedasticidad | Modelos Mixtos con R</title>
  <meta name="description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="12 Modelando la heterocedasticidad | Modelos Mixtos con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12 Modelando la heterocedasticidad | Modelos Mixtos con R" />
  
  <meta name="twitter:description" content="Este libro es para los estudiantes interesados en usar Modelos Mixtos." />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández Barajas" />
<meta name="author" content="Jorge Leonardo López Martínez" />


<meta name="date" content="2022-02-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reg-diagnos.html"/>
<link rel="next" href="glmm.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Mixtos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="reg-lin.html"><a href="reg-lin.html"><i class="fa fa-check"></i><b>1</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="1.1" data-path="reg-lin.html"><a href="reg-lin.html#modelo-estadístico"><i class="fa fa-check"></i><b>1.1</b> Modelo estadístico</a></li>
<li class="chapter" data-level="1.2" data-path="reg-lin.html"><a href="reg-lin.html#verosimilitud-del-modelo"><i class="fa fa-check"></i><b>1.2</b> Verosimilitud del modelo</a>
<ul>
<li class="chapter" data-level="" data-path="reg-lin.html"><a href="reg-lin.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lmm.html"><a href="lmm.html"><i class="fa fa-check"></i><b>2</b> Modelos Lineales Mixtos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lmm.html"><a href="lmm.html#entrevista-con-jim-ware-y-nan-laird"><i class="fa fa-check"></i><b>2.1</b> Entrevista con Jim Ware y Nan Laird</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>3</b> Aplicaciones shiny</a></li>
<li class="chapter" data-level="4" data-path="pac-lme4.html"><a href="pac-lme4.html"><i class="fa fa-check"></i><b>4</b> Paquete <strong>lme4</strong></a>
<ul>
<li class="chapter" data-level="4.1" data-path="pac-lme4.html"><a href="pac-lme4.html#función-lmer"><i class="fa fa-check"></i><b>4.1</b> Función <code>lmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-normal-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-recuperando-los-interceptos-aleatorios"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="4.2" data-path="pac-lme4.html"><a href="pac-lme4.html#función-glmer"><i class="fa fa-check"></i><b>4.2</b> Función <code>glmer</code></a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-gamma-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-lme4.html"><a href="pac-lme4.html#ejemplo-modelo-inversa-gaussiana-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i>Ejemplo: modelo inversa gaussiana con intercepto y pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="apli-lme4.html"><a href="apli-lme4.html"><i class="fa fa-check"></i><b>5</b> Aplicación con <code>lme4</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-lme4.html"><a href="apli-lme4.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="pac-nlme.html"><a href="pac-nlme.html"><i class="fa fa-check"></i><b>6</b> Paquete <strong>nlme</strong></a>
<ul>
<li class="chapter" data-level="6.1" data-path="pac-nlme.html"><a href="pac-nlme.html#función-lme"><i class="fa fa-check"></i><b>6.1</b> Función <code>lme</code></a></li>
<li class="chapter" data-level="" data-path="pac-nlme.html"><a href="pac-nlme.html#ejemplo-modelo-normal-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="apli-nlme.html"><a href="apli-nlme.html"><i class="fa fa-check"></i><b>7</b> Aplicación con <code>nlme</code></a>
<ul>
<li class="chapter" data-level="" data-path="apli-nlme.html"><a href="apli-nlme.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apli-rat-pup.html"><a href="apli-rat-pup.html"><i class="fa fa-check"></i><b>8</b> Aplicación rat pup</a></li>
<li class="chapter" data-level="9" data-path="estim.html"><a href="estim.html"><i class="fa fa-check"></i><b>9</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="9.1" data-path="estim.html"><a href="estim.html#ml-y-reml"><i class="fa fa-check"></i><b>9.1</b> ML y REML</a></li>
<li><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-lme4">Ejemplo: comparando REML y ML usando <strong>lme4</strong></a></li>
<li><a href="estim.html#ejemplo-comparando-reml-y-ml-usando-nlme">Ejemplo: comparando REML y ML usando <strong>nlme</strong></a></li>
<li class="chapter" data-level="" data-path="estim.html"><a href="estim.html#ejercicios-2"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>10</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ph.html"><a href="ph.html#prueba-razón-de-verosimilitud"><i class="fa fa-check"></i><b>10.1</b> Prueba razón de verosimilitud</a></li>
<li class="chapter" data-level="10.2" data-path="ph.html"><a href="ph.html#prueba-de-wald"><i class="fa fa-check"></i><b>10.2</b> Prueba de Wald</a></li>
<li class="chapter" data-level="10.3" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-sobre-los-efectos-fijos"><i class="fa fa-check"></i><b>10.3</b> Prueba de hipótesis sobre los efectos fijos</a>
<ul>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ph.html"><a href="ph.html#prueba-de-hipótesis-sobre-componentes-de-varianza"><i class="fa fa-check"></i><b>10.4</b> Prueba de hipótesis sobre componentes de varianza</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="ph.html"><a href="ph.html#componentes-de-varianza-lejos-del-borde"><i class="fa fa-check"></i><b>10.4.1</b> Componentes de varianza lejos del borde</a></li>
<li class="chapter" data-level="10.4.2" data-path="ph.html"><a href="ph.html#componentes-de-varianza-en-el-borde"><i class="fa fa-check"></i><b>10.4.2</b> Componentes de varianza en el borde</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph.html"><a href="ph.html#ejercicios-3"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reg-diagnos.html"><a href="reg-diagnos.html"><i class="fa fa-check"></i><b>11</b> Diagnóstico del modelo de regresión de efectos mixtos</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reg-diagnos.html"><a href="reg-diagnos.html#supuestos-del-modelo-de-regresión"><i class="fa fa-check"></i><b>11.1</b> Supuestos del modelo de regresión</a></li>
<li class="chapter" data-level="11.2" data-path="reg-diagnos.html"><a href="reg-diagnos.html#los-residuos"><i class="fa fa-check"></i><b>11.2</b> Los residuos</a></li>
<li class="chapter" data-level="11.3" data-path="reg-diagnos.html"><a href="reg-diagnos.html#diagnóstico-del-modelo-de-regresión-prueba-de-hipótesis-e-inferencia-visual"><i class="fa fa-check"></i><b>11.3</b> Diagnóstico del modelo de regresión: prueba de hipótesis e inferencia visual</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="reg-diagnos.html"><a href="reg-diagnos.html#ajustando-el-modelo"><i class="fa fa-check"></i><b>11.3.1</b> Ajustando el modelo</a></li>
<li class="chapter" data-level="11.3.2" data-path="reg-diagnos.html"><a href="reg-diagnos.html#varianza-constante-de-los-residuos-mediante-inferencia-visual"><i class="fa fa-check"></i><b>11.3.2</b> Varianza constante de los residuos mediante inferencia visual</a></li>
<li class="chapter" data-level="11.3.3" data-path="reg-diagnos.html"><a href="reg-diagnos.html#varianza-constante-de-los-residuos-mediante-prueba-de-hipótesis"><i class="fa fa-check"></i><b>11.3.3</b> Varianza constante de los residuos mediante prueba de hipótesis</a></li>
<li class="chapter" data-level="" data-path="reg-diagnos.html"><a href="reg-diagnos.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="11.3.4" data-path="reg-diagnos.html"><a href="reg-diagnos.html#distribución-normal-de-los-residuos-mediante-inferencia-visual"><i class="fa fa-check"></i><b>11.3.4</b> Distribución normal de los residuos mediante inferencia visual</a></li>
<li class="chapter" data-level="" data-path="reg-diagnos.html"><a href="reg-diagnos.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="11.3.5" data-path="reg-diagnos.html"><a href="reg-diagnos.html#distribución-normal-de-los-residuos-mediante-prueba-de-hipótesis"><i class="fa fa-check"></i><b>11.3.5</b> Distribución normal de los residuos mediante prueba de hipótesis</a></li>
<li class="chapter" data-level="11.3.6" data-path="reg-diagnos.html"><a href="reg-diagnos.html#gráfica-marginal-del-modelo"><i class="fa fa-check"></i><b>11.3.6</b> Gráfica marginal del modelo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="var-fun.html"><a href="var-fun.html"><i class="fa fa-check"></i><b>12</b> Modelando la heterocedasticidad</a>
<ul>
<li class="chapter" data-level="12.1" data-path="var-fun.html"><a href="var-fun.html#opciones-para-modelar-la-varianza"><i class="fa fa-check"></i><b>12.1</b> Opciones para modelar la varianza</a></li>
<li class="chapter" data-level="12.2" data-path="var-fun.html"><a href="var-fun.html#varfixed"><i class="fa fa-check"></i><b>12.2</b> varFixed</a></li>
<li><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cuantitativa">Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cuantitativa</a></li>
<li class="chapter" data-level="12.3" data-path="var-fun.html"><a href="var-fun.html#varident"><i class="fa fa-check"></i><b>12.3</b> varIdent</a></li>
<li><a href="var-fun.html#ejemplo-sigma2_y-dependiendo-de-una-variable-cualitativa">Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cualitativa</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>13</b> Modelos Lineales Generalizados Mixtos</a>
<ul>
<li class="chapter" data-level="13.1" data-path="glmm.html"><a href="glmm.html#videos-de-apoyo"><i class="fa fa-check"></i><b>13.1</b> Videos de apoyo</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html"><i class="fa fa-check"></i><b>14</b> Paquete <strong>glmmTMB</strong></a>
<ul>
<li class="chapter" data-level="14.1" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#función-glmmtmb"><i class="fa fa-check"></i><b>14.1</b> Función <code>glmmTMB</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-normal-con-intercepto-aleatorio-2"><i class="fa fa-check"></i>Ejemplo: modelo normal con intercepto aleatorio</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-recuperando-los-interceptos-aleatorios-1"><i class="fa fa-check"></i>Ejemplo: recuperando los interceptos aleatorios</a></li>
<li class="chapter" data-level="" data-path="pac-glmmTMB.html"><a href="pac-glmmTMB.html#ejemplo-modelo-gamma-con-intercepto-aleatorio-1"><i class="fa fa-check"></i>Ejemplo: modelo gamma con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pac-glmm.html"><a href="pac-glmm.html"><i class="fa fa-check"></i><b>15</b> Paquete <strong>glmm</strong></a>
<ul>
<li class="chapter" data-level="15.1" data-path="pac-glmm.html"><a href="pac-glmm.html#función-glmm"><i class="fa fa-check"></i><b>15.1</b> Función <code>glmm</code></a></li>
<li class="chapter" data-level="" data-path="pac-glmm.html"><a href="pac-glmm.html#ejemplo-modelo-poisson-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Poisson con intercepto aleatorio</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="pac-MASS.html"><a href="pac-MASS.html"><i class="fa fa-check"></i><b>16</b> Paquete <strong>MASS</strong></a>
<ul>
<li class="chapter" data-level="16.1" data-path="pac-MASS.html"><a href="pac-MASS.html#función-glmmpql"><i class="fa fa-check"></i><b>16.1</b> Función <code>glmmPQL</code></a></li>
<li class="chapter" data-level="" data-path="pac-MASS.html"><a href="pac-MASS.html#ejemplo-modelo-bernoulli-binomial-con-intercepto-aleatorio"><i class="fa fa-check"></i>Ejemplo: modelo Bernoulli (binomial) con intercepto aleatorio</a></li>
<li class="chapter" data-level="16.2" data-path="pac-MASS.html"><a href="pac-MASS.html#what-it-means-for-aic-na-in-glmmpql-mass-summary-output"><i class="fa fa-check"></i><b>16.2</b> what it means for AIC NA in glmmPQL (MASS) summary output?</a></li>
<li class="chapter" data-level="16.3" data-path="pac-MASS.html"><a href="pac-MASS.html#two-questions-on-the-results-from-glmmpqlmass"><i class="fa fa-check"></i><b>16.3</b> Two questions on the results from glmmPQL(MASS)</a></li>
<li class="chapter" data-level="16.4" data-path="pac-MASS.html"><a href="pac-MASS.html#how-do-i-interpret-the-variance-of-random-effect-in-a-generalized-linear-mixed-model"><i class="fa fa-check"></i><b>16.4</b> How do I interpret the variance of random effect in a generalized linear mixed model?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="glmm_poisson.html"><a href="glmm_poisson.html"><i class="fa fa-check"></i><b>17</b> GLMM Poisson</a></li>
<li class="chapter" data-level="18" data-path="glmm_gamma.html"><a href="glmm_gamma.html"><i class="fa fa-check"></i><b>18</b> GLMM gamma</a></li>
<li class="chapter" data-level="19" data-path="residuals.html"><a href="residuals.html"><i class="fa fa-check"></i><b>19</b> Diagnósticos con DHARMa</a>
<ul>
<li class="chapter" data-level="" data-path="residuals.html"><a href="residuals.html#ejemplo-modelo-gamma-mixto"><i class="fa fa-check"></i>Ejemplo: modelo gamma mixto</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="simul-glmm.html"><a href="simul-glmm.html"><i class="fa fa-check"></i><b>20</b> Simulación de glmm</a></li>
<li class="chapter" data-level="21" data-path="blobs.html"><a href="blobs.html"><i class="fa fa-check"></i><b>21</b> Otro material interesante</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Mixtos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="var-fun" class="section level1" number="12">
<h1><span class="header-section-number">12</span> Modelando la heterocedasticidad</h1>
<p>En este capítulo se mostrará como usar el paquete <code>nlme</code> de <span class="citation">Pinheiro, Bates, and R-core (<a href="#ref-R-nlme" role="doc-biblioref">2021</a>)</span> para modelar heterocedasticidad.</p>
<div id="opciones-para-modelar-la-varianza" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Opciones para modelar la varianza</h2>
<p>En la siguiente tabla se muestran las diferentes opciones para modelar la varianza <span class="math inline">\(\sigma^2_y\)</span> de la variable respuesta <span class="math inline">\(Y\)</span>.</p>
<table>
<thead>
<tr class="header">
<th>Clase</th>
<th>Modelo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>varFixed</td>
<td><span class="math inline">\(\sigma^2_y = \sigma^2 x_{ij}\)</span></td>
</tr>
<tr class="even">
<td>varIdent</td>
<td><span class="math inline">\(\sigma^2_y = \sigma^2 \delta^2_{Sij}\)</span></td>
</tr>
<tr class="odd">
<td>varPower</td>
<td><span class="math inline">\(\sigma^2_y = \sigma^2 |x_{ij}|^{2\delta}\)</span></td>
</tr>
<tr class="even">
<td>varExp</td>
<td><span class="math inline">\(\sigma^2_y = \sigma^2 e^{2 \delta x_{ij}}\)</span></td>
</tr>
<tr class="odd">
<td>varConstPower</td>
<td><span class="math inline">\(\sigma^2_y = \sigma^2 (\delta_1 + |x_{ij}|^{\delta_2})^2\)</span></td>
</tr>
<tr class="even">
<td>varComb</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="varfixed" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> varFixed</h2>
<p>En esta sección vamos a simular datos de un modelo lineal mixto en el cual <span class="math inline">\(\sigma^2_y\)</span> dependa de una variable cuantitativa para luego estimar los parámetros del modelo.</p>
</div>
<div id="ejemplo-sigma2_y-dependiendo-de-una-variable-cuantitativa" class="section level2 unnumbered">
<h2>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cuantitativa</h2>
<p>En este ejemplo vamos a simular observaciones <span class="math inline">\(n_i=10\)</span> observaciones para <span class="math inline">\(G=20\)</span> grupos (en total 200 obs) que tengan la estructura mostrada abajo. En este ejemplo la varianza <span class="math inline">\(\sigma^2_y\)</span> no es constante, depende de la varianza general <span class="math inline">\(\sigma^2=9\)</span> y de la variable <span class="math inline">\(X\)</span>, es decir <span class="math inline">\(\sigma^2_y = 9 \, x_{ij}\)</span>.</p>
<p><span class="math display">\[\begin{align*} 
y_{ij} | b_0 &amp;\sim  N(\mu_{ij}, \sigma^2_y) \\ 
\mu_{ij} &amp;= 4 - 6 x_{ij} + b_{0i} \\
\sigma^2_y &amp;= 9 \times x_{ij} \\
b_{0} &amp;\sim N(0, \sigma^2_{b0}=64) \\
x_{ij} &amp;\sim U(0, 200)
\end{align*}\]</span></p>
<p>El vector de parámetros de este modelo es <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0=4, \beta_1=-6, \sigma=3, \sigma_{b0}=8)^\top\)</span>.</p>
<div style="-moz-box-shadow: 1px 1px 3px 2px #000000;
  -webkit-box-shadow: 1px 1px 3px 2px #000000;
  box-shadow:         1px 1px 3px 2px #000000;">

<div class="rmdexercise">
Solución.
</div>
</div>
<p>El código para simular las 500 observaciones se muestra a continuación. Observe que se fijó la semilla para que el lector pueda replicar el ejemplo y obtener los mismos resultados.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="var-fun.html#cb1-1" aria-hidden="true" tabindex="-1"></a>ni <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1-2"><a href="var-fun.html#cb1-2" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb1-3"><a href="var-fun.html#cb1-3" aria-hidden="true" tabindex="-1"></a>nobs <span class="ot">&lt;-</span> ni <span class="sc">*</span> G</span>
<span id="cb1-4"><a href="var-fun.html#cb1-4" aria-hidden="true" tabindex="-1"></a>grupo <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>G, <span class="at">each=</span>ni))</span>
<span id="cb1-5"><a href="var-fun.html#cb1-5" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>ni, <span class="at">times=</span>G)</span>
<span id="cb1-6"><a href="var-fun.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-7"><a href="var-fun.html#cb1-7" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>nobs, <span class="at">min=</span><span class="dv">0</span>, <span class="at">max=</span><span class="dv">200</span>)</span>
<span id="cb1-8"><a href="var-fun.html#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-9"><a href="var-fun.html#cb1-9" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>G, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="fu">sqrt</span>(<span class="dv">64</span>)) <span class="co"># Intercepto aleatorio</span></span>
<span id="cb1-10"><a href="var-fun.html#cb1-10" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span>b0, <span class="at">each=</span>ni)              <span class="co"># El mismo intercepto aleatorio pero repetido</span></span>
<span id="cb1-11"><a href="var-fun.html#cb1-11" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> x <span class="sc">+</span> b0</span>
<span id="cb1-12"><a href="var-fun.html#cb1-12" aria-hidden="true" tabindex="-1"></a>sigma2_y <span class="ot">&lt;-</span> <span class="dv">9</span> <span class="sc">*</span> x</span>
<span id="cb1-13"><a href="var-fun.html#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-14"><a href="var-fun.html#cb1-14" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>nobs, <span class="at">mean=</span>media, <span class="at">sd=</span><span class="fu">sqrt</span>(sigma2_y))</span>
<span id="cb1-15"><a href="var-fun.html#cb1-15" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(obs, grupo, x, y)</span></code></pre></div>
<p>Primero vamos a ajustar un modelo <code>fit0</code> que asume varianza <span class="math inline">\(\sigma^2_y\)</span> constante para compararlo con el modelo <code>fit1</code> que si modela la varianza en función de la covariable <span class="math inline">\(X\)</span>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="var-fun.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb2-2"><a href="var-fun.html#cb2-2" aria-hidden="true" tabindex="-1"></a>fit0 <span class="ot">&lt;-</span> <span class="fu">lme</span>(y <span class="sc">~</span> x, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> grupo, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Vamos a explorar el gráfico de residuales versus la covariable <span class="math inline">\(X\)</span> para ver si hay un indicio de heterocedasticidad (varianza no costante).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="var-fun.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit0, <span class="fu">resid</span>(., <span class="at">type =</span> <span class="st">&quot;p&quot;</span>) <span class="sc">~</span> x, <span class="at">abline =</span> <span class="dv">0</span>, <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>De la figura anterior vemos claramente una forma de “corneta”, cerrada a izquierda y abierta a la derecha, esto es un indicio de que se debe modelar la varianza <span class="math inline">\(\sigma^2_y\)</span>.</p>
<p>El siguiente modelo permite que la varianza <span class="math inline">\(\sigma^2_y\)</span> sea función de <span class="math inline">\(X\)</span> usando una estructura <code>varFixed</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="var-fun.html#cb4-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lme</span>(y <span class="sc">~</span> x, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> grupo, <span class="at">weights=</span><span class="fu">varFixed</span>(<span class="sc">~</span> x), <span class="at">data=</span>datos)</span></code></pre></div>
<p>A continuación repetimos la misma figura de residuales anterior. De esta figura logramos ver que se eliminó el patrón de “corneta” observado antes.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="var-fun.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit1, <span class="fu">resid</span>(., <span class="at">type =</span> <span class="st">&quot;p&quot;</span>) <span class="sc">~</span> x, <span class="at">abline =</span> <span class="dv">0</span>, <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>La función <code>summary</code> se puede usar sobre el objeto <code>fit1</code> para obtener una tabla de resumen, a continuación se ilustra el uso y la salida de <code>summary</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="var-fun.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: datos 
##        AIC      BIC    logLik
##   1886.683 1899.836 -939.3417
## 
## Random effects:
##  Formula: ~1 | grupo
##         (Intercept) Residual
## StdDev:    7.182138 2.841913
## 
## Variance function:
##  Structure: fixed weights
##  Formula: ~x 
## Fixed effects:  y ~ x 
##                 Value Std.Error  DF    t-value p-value
## (Intercept)  4.262272 2.7075258 179    1.57423  0.1172
## x           -5.994199 0.0293592 179 -204.16788  0.0000
##  Correlation: 
##   (Intr)
## x -0.59 
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.44109665 -0.63620797 -0.05268718  0.61698526  3.36214890 
## 
## Number of Observations: 200
## Number of Groups: 20</code></pre>
<p>Según el resultado anterior <span class="math inline">\(\hat{\boldsymbol{\Theta}}=(\hat{\beta}_0=4.2623, \hat{\beta}_1=-5.9942, \hat{\sigma}=2.8419, \hat{\sigma}_{b0}=7.1821)^\top\)</span> mientras que el vector real de parámetros es <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0=4, \beta_1=-6, \sigma=3, \sigma_{b0}=8)^\top\)</span>.</p>
<p>En el código de abajo usamos la función <code>anova.lme</code> para comparar los dos modelos anteriores. Del resultado vemos que ambos modelos tienen 4 parámetros y que el modelo <code>fit1</code> tiene el menor valor de BIC y mayor valor de verosimilitud, esto indica que el modelo <code>fit1</code> es más apropiado para modelar los datos.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="var-fun.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit0, fit1)</span></code></pre></div>
<pre><code>##      Model df      AIC      BIC    logLik
## fit0     1  4 1912.618 1925.771 -952.3089
## fit1     2  4 1886.683 1899.836 -939.3417</code></pre>
<div style="-moz-box-shadow: 1px 1px 3px 2px #00ffff;
  -webkit-box-shadow: 1px 1px 3px 2px #00ffff;
  box-shadow:         1px 1px 3px 2px #00ffff;">

<div class="rmdtip">
La varianza <span class="math inline">\(\sigma^2_y\)</span> se puede modelar también para modelos lineales, se le recomienda al lector consultar los siguiente enlaces para ver ejemplos: <a href="https://data.library.virginia.edu/modeling-non-constant-variance/" class="uri">https://data.library.virginia.edu/modeling-non-constant-variance/</a> y <a href="https://pegasus.uprm.edu/~pedro.torres/book/chapter3.html#modelo-con-varianza-heterogenea" class="uri">https://pegasus.uprm.edu/~pedro.torres/book/chapter3.html#modelo-con-varianza-heterogenea</a>
</div>
</div>
</div>
<div id="varident" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> varIdent</h2>
<p>En esta sección vamos a simular datos de un modelo lineal mixto en el cual <span class="math inline">\(\sigma^2_y\)</span> dependa de una variable cualitativa para luego estimar los parámetros del modelo.</p>
</div>
<div id="ejemplo-sigma2_y-dependiendo-de-una-variable-cualitativa" class="section level2 unnumbered">
<h2>Ejemplo: <span class="math inline">\(\sigma^2_y\)</span> dependiendo de una variable cualitativa</h2>
<p>En este ejemplo vamos a simular observaciones <span class="math inline">\(n_i=10\)</span> observaciones para <span class="math inline">\(G=20\)</span> grupos (en total 200 obs) que tengan la estructura mostrada abajo. En este ejemplo la varianza <span class="math inline">\(\sigma^2_y\)</span> no es constante, depende de la varianza general <span class="math inline">\(\sigma^2=9\)</span> y de la variable sexo, para los hombres la varianza será <span class="math inline">\(\sigma^2_y = 9 * \delta_H\)</span> y para las mujeres la varianza será <span class="math inline">\(\sigma^2_y = 9 * \delta_M\)</span>. Los valores de <span class="math inline">\(\delta\)</span> a usar en la simulación son <span class="math inline">\(\delta_H=1\)</span> y <span class="math inline">\(\delta_M=6\)</span>, esto para hacer que las observaciones de la mujeres tengan mayor variabilidad.</p>
<p>El modelo de interés se puede resumir de la siguiente manera.</p>
<p><span class="math display">\[\begin{align*} 
y_{ij} | b_0 &amp;\sim  N(\mu_{ij}, \sigma^2_y) \\ 
\mu_{ij} &amp;= 4 - 6 x_{ij} + b_{0i} \\
\text{Hombre} \quad \sigma^2_y &amp;= 9 \times 1 \\
\text{Mujer} \quad \sigma^2_y &amp;= 9 \times 6 \\
b_{0} &amp;\sim N(0, \sigma^2_{b0}=64) \\
x_{ij} &amp;\sim U(0, 200)
\end{align*}\]</span></p>
<p>El vector de parámetros de este modelo es <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0=4, \beta_1=-6, \sigma=3, \delta_H=1, \delta_H=6, \sigma_{b0}=8)^\top\)</span>.</p>
<div style="-moz-box-shadow: 1px 1px 3px 2px #000000;
  -webkit-box-shadow: 1px 1px 3px 2px #000000;
  box-shadow:         1px 1px 3px 2px #000000;">

<div class="rmdexercise">
Solución.
</div>
</div>
<p>El código para simular las 500 observaciones se muestra a continuación. Observe que se fijó la semilla para que el lector pueda replicar el ejemplo y obtener los mismos resultados.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="var-fun.html#cb10-1" aria-hidden="true" tabindex="-1"></a>ni <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb10-2"><a href="var-fun.html#cb10-2" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb10-3"><a href="var-fun.html#cb10-3" aria-hidden="true" tabindex="-1"></a>nobs <span class="ot">&lt;-</span> ni <span class="sc">*</span> G</span>
<span id="cb10-4"><a href="var-fun.html#cb10-4" aria-hidden="true" tabindex="-1"></a>grupo <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>G, <span class="at">each=</span>ni))</span>
<span id="cb10-5"><a href="var-fun.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-6"><a href="var-fun.html#cb10-6" aria-hidden="true" tabindex="-1"></a>sexo <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="st">&quot;Hombre&quot;</span>, <span class="st">&quot;Mujer&quot;</span>), <span class="at">size=</span>nobs, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb10-7"><a href="var-fun.html#cb10-7" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span>ni, <span class="at">times=</span>G)</span>
<span id="cb10-8"><a href="var-fun.html#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-9"><a href="var-fun.html#cb10-9" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>nobs, <span class="at">min=</span><span class="dv">0</span>, <span class="at">max=</span><span class="dv">200</span>)</span>
<span id="cb10-10"><a href="var-fun.html#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-11"><a href="var-fun.html#cb10-11" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>G, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="fu">sqrt</span>(<span class="dv">64</span>)) <span class="co"># Intercepto aleatorio</span></span>
<span id="cb10-12"><a href="var-fun.html#cb10-12" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x=</span>b0, <span class="at">each=</span>ni)              <span class="co"># El mismo intercepto aleatorio pero repetido</span></span>
<span id="cb10-13"><a href="var-fun.html#cb10-13" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> x <span class="sc">+</span> b0</span>
<span id="cb10-14"><a href="var-fun.html#cb10-14" aria-hidden="true" tabindex="-1"></a>delta_h <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-15"><a href="var-fun.html#cb10-15" aria-hidden="true" tabindex="-1"></a>delta_m <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb10-16"><a href="var-fun.html#cb10-16" aria-hidden="true" tabindex="-1"></a>sigma2_y <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sexo <span class="sc">==</span> <span class="st">&quot;Hombre&quot;</span>, <span class="dv">9</span> <span class="sc">*</span> delta_h<span class="sc">^</span><span class="dv">2</span>, <span class="dv">9</span> <span class="sc">*</span> delta_m<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb10-17"><a href="var-fun.html#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-18"><a href="var-fun.html#cb10-18" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>nobs, <span class="at">mean=</span>media, <span class="at">sd=</span><span class="fu">sqrt</span>(sigma2_y))</span>
<span id="cb10-19"><a href="var-fun.html#cb10-19" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(obs, grupo, sexo, x, y)</span></code></pre></div>
<p>Primero vamos a ajustar un modelo <code>fit0</code> que asume varianza <span class="math inline">\(\sigma^2_y\)</span> constante para compararlo con el modelo <code>fit1</code> que si modela la varianza en función de la covariable sexo.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="var-fun.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb11-2"><a href="var-fun.html#cb11-2" aria-hidden="true" tabindex="-1"></a>fit0 <span class="ot">&lt;-</span> <span class="fu">lme</span>(y <span class="sc">~</span> x, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> grupo, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Vamos a explorar el gráfico de residuales versus la covariable sexo para ver si hay un indicio de heterocedasticidad (varianza no costante).</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="var-fun.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit0, <span class="fu">resid</span>(., <span class="at">type =</span> <span class="st">&quot;p&quot;</span>) <span class="sc">~</span> x <span class="sc">|</span> sexo, <span class="at">abline =</span> <span class="dv">0</span>, <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>De la figura anterior vemos claramente los residuales no se comportan igual para hombres y mujeres, esto es un indicio de que se debe modelar la varianza <span class="math inline">\(\sigma^2_y\)</span> teniendo en cuenta el sexo.</p>
<p>El siguiente modelo permite que la varianza <span class="math inline">\(\sigma^2_y\)</span> sea función del sexo usando una estructura <code>varIdent</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="var-fun.html#cb13-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lme</span>(y <span class="sc">~</span> x, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> grupo, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span><span class="sc">|</span> sexo), </span>
<span id="cb13-2"><a href="var-fun.html#cb13-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>datos)</span></code></pre></div>
<p>A continuación repetimos la misma figura de residuales anterior. De esta figura logramos ver que se eliminó el patrón observado antes.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="var-fun.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit1, <span class="fu">resid</span>(., <span class="at">type =</span> <span class="st">&quot;p&quot;</span>) <span class="sc">~</span> x <span class="sc">|</span> sexo, <span class="at">abline =</span> <span class="dv">0</span>, <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div>
<p><img src="libro_mod_mixtos_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>La función <code>summary</code> se puede usar sobre el objeto <code>fit1</code> para obtener una tabla de resumen, a continuación se ilustra el uso y la salida de <code>summary</code>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="var-fun.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: datos 
##        AIC      BIC    logLik
##   1413.453 1429.895 -701.7267
## 
## Random effects:
##  Formula: ~1 | grupo
##         (Intercept) Residual
## StdDev:    7.844797  2.62634
## 
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | sexo 
##  Parameter estimates:
##   Hombre    Mujer 
## 1.000000 6.725537 
## Fixed effects:  y ~ x 
##                 Value Std.Error  DF    t-value p-value
## (Intercept)  3.917506 1.8639114 179     2.1018   0.037
## x           -5.990032 0.0054473 179 -1099.6411   0.000
##  Correlation: 
##   (Intr)
## x -0.305
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.01600189 -0.58592550 -0.02227228  0.49152791  3.26640788 
## 
## Number of Observations: 200
## Number of Groups: 20</code></pre>
<p>Según el resultado anterior <span class="math inline">\(\hat{\boldsymbol{\Theta}}=(\hat{\beta}_0=3.92, \hat{\beta}_1=-5.99, \hat{\sigma}=2.63, \hat{\delta}_H=1, \hat{\delta}_M=6.73, \hat{\sigma}_{b0}=7.84)^\top\)</span> mientras que el vector real de parámetros es <span class="math inline">\(\boldsymbol{\Theta}=(\beta_0=4, \beta_1=-6, \sigma=3, \delta_H=1, \delta_H=6, \sigma_{b0}=8)^\top\)</span>.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-nlme" class="csl-entry">
Pinheiro, José, Douglas Bates, and R-core. 2021. <em>Nlme: Linear and Nonlinear Mixed Effects Models</em>. <a href="https://svn.r-project.org/R-packages/trunk/nlme/">https://svn.r-project.org/R-packages/trunk/nlme/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reg-diagnos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="glmm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_modelos_mixtos/edit/master/340-var-fun.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
